; File initially autogenerated by ./scripts/dump_tilesets.py

SECTION "Tileset Font1", ROMX[$4000], BANK[$08]
TilesetFont1::
  INCBIN "./build/gfx/tilesets/Font1.1bpp"
SECTION "Tileset Font1 End", ROMX[$7FFF], BANK[$08]

SECTION "Tileset Font2", ROMX[$4000], BANK[$09]
TilesetFont2::
  INCBIN "./build/gfx/tilesets/Font2.1bpp"
SECTION "Tileset Font2 End", ROMX[$7FFF], BANK[$09]

SECTION "Tileset Font3", ROMX[$4000], BANK[$0A]
TilesetFont3::
  INCBIN "./build/gfx/tilesets/Font3.1bpp"
SECTION "Tileset Font3 End", ROMX[$7FFF], BANK[$0A]

SECTION "Tileset DoubleHeightFont1", ROMX[$4110], BANK[$06]
TilesetDoubleHeightFont1::
  INCBIN "./build/gfx/tilesets/DoubleHeightFont1.1bpp"
SECTION "Tileset DoubleHeightFont1 End", ROMX[$518F], BANK[$06]

SECTION "Tileset DoubleHeightFont2", ROMX[$6000], BANK[$06]
TilesetDoubleHeightFont2::
  INCBIN "./build/gfx/tilesets/DoubleHeightFont2.1bpp"
SECTION "Tileset DoubleHeightFont2 End", ROMX[$7FFF], BANK[$06]

SECTION "Tileset DoubleHeightFont3", ROMX[$4000], BANK[$07]
TilesetDoubleHeightFont3::
  INCBIN "./build/gfx/tilesets/DoubleHeightFont3.1bpp"
SECTION "Tileset DoubleHeightFont3 End", ROMX[$6EAF], BANK[$07]

SECTION "Tileset TitleScreen1", ROMX[$7246], BANK[$3B]
TilesetTitleScreen1::
  INCBIN "./build/gfx/tilesets/TitleScreen1.compressed.2bpp.compressed"
SECTION "Tileset TitleScreen1 End", ROMX[$7267], BANK[$3B]

SECTION "Tileset TitleScreen2", ROMX[$72EA], BANK[$37]
TilesetTitleScreen2::
  INCBIN "./build/gfx/tilesets/TitleScreen2.compressed.2bpp.compressed"
SECTION "Tileset TitleScreen2 End", ROMX[$79E5], BANK[$37]

SECTION "Tileset TitleScreen3", ROMX[$6D43], BANK[$38]
TilesetTitleScreen3::
  INCBIN "./build/gfx/tilesets/TitleScreen3.compressed.2bpp.compressed"
SECTION "Tileset TitleScreen3 End", ROMX[$725C], BANK[$38]

