; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 2E", ROMX[$4B2C], BANK[$23]
GameScene2E::
  dw GameSceneScript00C1
  dw GameSceneScript00C2
  dw GameSceneScript00C3
  dw GameSceneScript00C4
  dw $0000
