; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 1B", ROMX[$46BB], BANK[$23]
GameScene1B::
  dw GameSceneScript005E
  dw GameSceneScript005F
  dw GameSceneScript0060
  dw GameSceneScript0061
  dw GameSceneScript0062
  dw GameSceneScript0063
  dw GameSceneScript0064
  dw GameSceneScript0065
  dw GameSceneScript0067
  dw GameSceneScript0068
  dw GameSceneScript0069
  dw GameSceneScript006A
  dw GameSceneScript0066
  dw GameSceneScript006B
  dw $0000
