; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 44", ROMX[$4DF3], BANK[$23]
GameScene44::
  dw GameSceneScript0103
  dw GameSceneScript0105
  dw GameSceneScript0104
  dw $0000
