; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 7E", ROMX[$5650], BANK[$23]
GameScene7E::
  dw GameSceneScript01C2
  dw GameSceneScript01C3
  dw GameSceneScript01C0
  dw GameSceneScript01C1
  dw $0000
