; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene A7", ROMX[$5FB1], BANK[$23]
GameSceneA7::
  dw GameSceneScript0292
  dw GameSceneScript0293
  dw GameSceneScript0294
  dw GameSceneScript0291
  dw $0000
