; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene A5", ROMX[$5F65], BANK[$23]
GameSceneA5::
  dw GameSceneScript0289
  dw GameSceneScript028A
  dw GameSceneScript028B
  dw GameSceneScript028C
  dw GameSceneScript028D
  dw GameSceneScript028E
  dw $0000
