; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 77", ROMX[$556A], BANK[$23]
GameScene77::
  dw GameSceneScript01AD
  dw GameSceneScript01AE
  dw GameSceneScript01AF
  dw GameSceneScript01AB
  dw GameSceneScript01AC
  dw $0000
