; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 60", ROMX[$51B1], BANK[$23]
GameScene60::
  dw GameSceneScript015A
  dw GameSceneScript015B
  dw GameSceneScript0159
  dw $0000
