; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 61", ROMX[$51D0], BANK[$23]
GameScene61::
  dw GameSceneScript015C
  dw GameSceneScript015D
  dw GameSceneScript015E
  dw GameSceneScript015F
  dw $0000
