; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 78", ROMX[$55A0], BANK[$23]
GameScene78::
  dw GameSceneScript01B0
  dw GameSceneScript01B1
  dw GameSceneScript01B2
  dw GameSceneScript01B3
  dw $0000
