; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 93", ROMX[$5B4A], BANK[$23]
GameScene93::
  dw GameSceneScript022C
  dw GameSceneScript022D
  dw GameSceneScript022E
  dw $0000
