; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 6F", ROMX[$5454], BANK[$23]
GameScene6F::
  dw GameSceneScript0192
  dw GameSceneScript0193
  dw GameSceneScript0194
  dw GameSceneScript0195
  dw $0000
