; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 5B", ROMX[$511B], BANK[$23]
GameScene5B::
  dw GameSceneScript014B
  dw GameSceneScript014C
  dw GameSceneScript014D
  dw $0000
