; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 6B", ROMX[$5371], BANK[$23]
GameScene6B::
  dw GameSceneScript0181
  dw GameSceneScript0182
  dw GameSceneScript017D
  dw GameSceneScript017E
  dw GameSceneScript017F
  dw GameSceneScript0180
  dw $0000
