; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene A8", ROMX[$5FDB], BANK[$23]
GameSceneA8::
  dw GameSceneScript0295
  dw GameSceneScript0296
  dw GameSceneScript0297
  dw GameSceneScript0298
  dw $0000
