; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 49", ROMX[$4EA2], BANK[$23]
GameScene49::
  dw GameSceneScript0112
  dw GameSceneScript0113
  dw GameSceneScript0114
  dw $0000
