; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 75", ROMX[$5502], BANK[$23]
GameScene75::
  dw GameSceneScript01A2
  dw GameSceneScript01A3
  dw GameSceneScript01A4
  dw GameSceneScript01A5
  dw $0000
