; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 00", ROMX[$4292], BANK[$23]
GameScene00::
  dw GameSceneScript0000
  dw GameSceneScript0001
  dw GameSceneScript0002
  dw $0000
