; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 55", ROMX[$5063], BANK[$23]
GameScene55::
  dw GameSceneScript0139
  dw GameSceneScript013A
  dw GameSceneScript013B
  dw $0000
