; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 81", ROMX[$569F], BANK[$23]
GameScene81::
  dw GameSceneScript01CC
  dw GameSceneScript01CD
  dw GameSceneScript01CE
  dw GameSceneScript01CF
  dw GameSceneScript01C8
  dw GameSceneScript01C9
  dw GameSceneScript01CA
  dw GameSceneScript01CB
  dw GameSceneScript01D0
  dw GameSceneScript01D1
  dw GameSceneScript01D2
  dw $0000
