; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 82", ROMX[$571E], BANK[$23]
GameScene82::
  dw GameSceneScript01D3
  dw GameSceneScript01D9
  dw GameSceneScript01DA
  dw GameSceneScript01D5
  dw GameSceneScript01D6
  dw GameSceneScript01D7
  dw GameSceneScript01D8
  dw GameSceneScript01DB
  dw GameSceneScript01DC
  dw GameSceneScript01DD
  dw GameSceneScript01D4
  dw $0000
