; File initially autogenerated by ./scripts/dump_gamescene_scripts.py
SECTION "Game Scene 31", ROMX[$4B90], BANK[$23]
GameScene31::
  dw GameSceneScript00CB
  dw GameSceneScript00CC
  dw GameSceneScript00CD
  dw GameSceneScript00CE
  dw $0000
