#!/bin/python
import os
import struct
import sys
from collections import OrderedDict
from functools import partial

sys.path.append(os.path.join(os.path.dirname(__file__), 'common'))
from common import utils, gfx

# The set of [ADDR:2LE][BANK:1] is relative to 0x4000 but the first actual index is 0x11
TABLE_START = (0x40, 0x4000)
INITIAL_BANK = 0x41
FINAL_ADDR = (0x4E, 0x4495) # Don't have a better way to get this for now, might need to revisit
TABLE_COUNT = 0x5F

class CommandFunction:
    # Params must be tuples of the form (Name, '<struct format string>')
    def __init__(self, name, special_handler, *params):
        self.name = name
        self.special_handler = special_handler
        self.parameters = OrderedDict(params)
        self.parameter_format = "".join(self.parameters.values())
        if not special_handler:
            self.parameter_size = struct.calcsize(self.parameter_format)
        else:
            self.parameter_size = 0 # Let handler set this

# Generate a dummy command based on the number of bytes it reads
def generate_dummy_command(name, num_param_bytes):
    return CommandFunction(name, None, *[(f"Unknown{x}", "B") for x in range(num_param_bytes)])


# TODO: Return length and an ordered dict of parameters
def ParseLIPSTimed(data):
    # Arg1: Available Time (lower is less time)
    # Arg2: Number of options
    length = 1 + 1
    num_options = data[1]
    assert num_options <= 3
    while num_options > 0:
        length += len(list(iter(partial((iter(data[length:]).__next__)), 0)))
        length += 1 + 1 # Count the End code and the flag as well
        num_options -= 1
    return length

# Command lengths were determined by using 18:436F and CBE2 to see when commands were being parsed
# 18:436F gets called to figure out which handler to use for the command
# CBE2 contains information about what's currently executing
COMMANDS = {}
COMMANDS[0x00] = generate_dummy_command("End", 1)
COMMANDS[0x01] = CommandFunction("WriteText",
    # There's probably a nicer way to do this iter
    lambda data: len(list(iter(partial((iter(data).__next__)), 0))) + 1
)
COMMANDS[0x02] = generate_dummy_command("Unknown02", 0)
COMMANDS[0x07] = CommandFunction("Unknown07",
    lambda data: len(list(iter(partial((iter(data).__next__)), 0))) + 1
)
COMMANDS[0x09] = generate_dummy_command("Unknown09", 1)
COMMANDS[0x0A] = generate_dummy_command("PromptContinue", 0)
COMMANDS[0x0C] = generate_dummy_command("Unknown0C", 1)
COMMANDS[0x0E] = generate_dummy_command("Unknown0E", 1)
COMMANDS[0x0F] = generate_dummy_command("Unknown0F", 2)
COMMANDS[0x12] = generate_dummy_command("Unknown12", 1)
COMMANDS[0x16] = CommandFunction("LIPSTimed", ParseLIPSTimed)
COMMANDS[0x19] = generate_dummy_command("SetPortrait", 3) # Need to verify
COMMANDS[0x1D] = generate_dummy_command("Unknown1D", 0)


# Arguments
script_name = sys.argv[0]
rom_path = sys.argv[1]
game_cutscene_src_dir = sys.argv[2]

# Derive file paths
cutscene_table_path = os.path.join(game_cutscene_src_dir, "cutscene_script_table.asm")
commands_src_path = os.path.join(game_cutscene_src_dir, "include/commands.asm")

with open(commands_src_path, "w") as output:
    output.write(f"; Autogenerated by {sys.argv[0]}\n\n")
    for symbol in COMMANDS:
        command = COMMANDS[symbol]
        output.write(f"MACRO {command.name}\n")
        output.write(f"  db ${symbol:02X}")

        if command.special_handler is not None:
            # Assume that a special handler means a non-zero number of subsequent bytes
            output.write(', \\#\n')
        else:
            for i in range(command.parameter_size):
                output.write(f"\n  db \\{i + 1}")
            else:
                output.write('\n')
        output.write("ENDM\n\n")    

with open(rom_path, 'rb') as rom:
    script_addresses = OrderedDict()
    # Build the addresses first since we need to get the end address
    for index in range(0, TABLE_COUNT):
        rom.seek(utils.rom2realaddr(TABLE_START) + (index * 3))
        addr = utils.read_short(rom) + 0x4000
        bank = utils.read_byte(rom) + INITIAL_BANK
        script_addresses[index] = (bank, addr)
    script_addresses[TABLE_COUNT] = FINAL_ADDR

    # Start dumping scripts
    for index, (bank, addr) in script_addresses.items():
        if index == TABLE_COUNT or (bank == INITIAL_BANK and addr == 0x4000):
            continue
        with open(os.path.join(game_cutscene_src_dir, f"cutscene_script_{index:02X}.asm"), "w") as source_fp:
            source_fp.write(f"; File initially autogenerated by {script_name}\n")
            source_fp.write('\n')
            source_fp.write(f'INCLUDE "{commands_src_path}"\n\n')
            name = f"CutsceneScript{index:02X}"

            start_addr = utils.rom2realaddr((bank, addr))
            end_addr = utils.rom2realaddr(script_addresses[index + 1])
            rom.seek(start_addr)
            data = rom.read(end_addr - start_addr)

            # Note that data can go over the bank limit, so we need to properly handle overflow into the next bank

            current_offset = 0
            iteration = 0
            while current_offset < len(data):
                bytes_in_bank = 0x8000 - addr
                source_fp.write(f'SECTION "Cutscene Script {index:02X} {iteration}", ROMX[${addr:04X}], BANK[${bank:02X}]\n')
                source_fp.write(f"{name}_{iteration}::\n")
                # Simplify reference
                code_data = data[current_offset:current_offset + bytes_in_bank]
                # Parse each byte of the script to generate a list of script functions
                command_overflow = 0
                i = 0
                while i < len(code_data):
                    # Write out command overflow, with the assumption that we won't overflow immediately
                    if command_overflow > 0:
                        source_fp.write(f"  db {','.join([f'${x:02X}' for x in code_data[i:i+command_overflow]])}\n")
                        i += command_overflow

                    command = COMMANDS[code_data[i]]
                    i += 1
                    # Scripts can overflow into the next bank, so in this case we have to be careful
                    parameter_size = command.parameter_size if command.special_handler is None else command.special_handler(code_data[i:])
                    if parameter_size + i > len(code_data):
                        command_overflow = parameter_size + i - len(code_data)
                        amount_to_read = parameter_size-command_overflow
                        source_fp.write(f"  db {','.join([f'${x:02X}' for x in code_data[i:i+amount_to_read]])}\n")
                        i += amount_to_read
                    else:
                        source_fp.write(f"  {command.name}")
                        if parameter_size > 0:
                            source_fp.write(" ")
                        params = [f"${x:02X}" for x in code_data[i:i+parameter_size]]
                        i += parameter_size
                        source_fp.write(",".join(params))
                        source_fp.write('\n')


                source_fp.write(f"{name}_{iteration}End::\n")
                bank += 1
                addr = 0x4000
                current_offset += bytes_in_bank
                iteration += 1
                source_fp.write('\n\n')

with open(cutscene_table_path, 'w') as source_fp:
    source_fp.write(f"; File initially autogenerated by {script_name}\n")
    source_fp.write('\n')
    source_fp.write('INCLUDE "game/src/common/macros.asm"\n\n')

    source_fp.write(f'SECTION "Cutscene Script Table", ROMX[${TABLE_START[1]:04X}], BANK[${TABLE_START[0]:02X}]\n')
    source_fp.write(f'EventCutsceneScriptTable::\n')
    for index, (bank, addr) in script_addresses.items():
        if index == TABLE_COUNT:
            continue
        if bank == INITIAL_BANK and addr == 0x4000:
            source_fp.write('  dwb $0000, $00\n')
        else:
            name = f"CutsceneScript{index:02X}_0"
            source_fp.write(f'  dwb {name} - $4000, BANK({name}) - ${INITIAL_BANK:02X}\n')