#!/bin/python

import os
import sys
import csv
import io
from ast import literal_eval
from collections import OrderedDict

sys.path.append(os.path.join(os.path.dirname(__file__), 'common'))
from common import utils, gfx

script_name = sys.argv[0]
output_file = sys.argv[1]
charmap_file = sys.argv[2] # Should be a better way to do this...
sections_file = sys.argv[3] 
text_section_file = sys.argv[4]
input_csvs = sys.argv[5:]

# We really only need the lengths, so we'll do this quick
character_length_table = {}
with open(charmap_file, 'r', encoding='utf-8') as fp:
    c = io.StringIO(fp.read().replace('CHARMAP ', ''))
    reader = csv.reader(c, delimiter=',', quotechar='"')
    for line in reader:
        assert line[0] not in character_length_table, f"Duplicate character in map: '{line[0]}', {character_length_table}"
        character_length_table[line[0]] = len(line) - 1

# Order matters here
sections_table = OrderedDict()
with open(sections_file, 'r', encoding='utf-8') as fp:
    for line in fp:
        line = line.strip().split('=')
        section_idx = int(line[0])
        value = literal_eval(line[1])
        assert type(value) is tuple
        if type(value[0]) is tuple:
            value = (utils.rom2realaddr(value[0]), value[1])
        sections_table[section_idx] = value

sections_size = { int(key): sections_table[key][1] for key in sections_table }

text_section_table = OrderedDict()
with open(text_section_file, 'r', encoding='utf-8') as fp:
    for line in fp:
        line = line.strip().split('=')
        text_section_table[line[0]] = line[1]

with open(output_file, 'w', encoding='utf-8') as output_fp:
    output_fp.write(f'; Autogenerated by {script_name}\n\n')
    output_fp.write(f'PUSHC\n')

    output_fp.write(f'INCLUDE "{charmap_file}"\n\n')

    text_lengths = {}

    for input_csv in input_csvs:
        with open(input_csv, 'r', encoding='utf-8') as input_fp:
            reader = csv.reader(input_fp, delimiter=',', quotechar='"')
            header = next(reader, None)
            index_ID = header.index("ID")
            index_text = header.index("Text")

            for line in reader:
                # Comment
                if line[0].startswith('#'):
                    continue

                ID = line[index_ID]
                text = line[index_text]

                # Note length +_one character for the terminator
                text_lengths[ID] = sum(utils.txt2bin(text, character_length_table)) + 1
                output_fp.write(f'DEF {ID} EQUS "{text.replace('"','\"')}"\n')

    for section_idx in sections_table:
        bank, addr = utils.real2romaddr(sections_table[section_idx][0])
        output_fp.write(f'\nSECTION "Gamescene NPC Data Section {section_idx:04X}", ROMX[${addr:04X}], BANK[${bank:02X}]\n')
        # Read the ordered dictionary to find everything that can fit in this section
        for k in text_section_table:
            if text_section_table[k] == '*' and text_lengths[f'c{k}'] <= sections_size[section_idx]:
                # Greedily put it wherever it can fit
                output_fp.write(f'{k}::\n')
                output_fp.write(f'  db #c{k},$00\n')
                sections_size[section_idx] -= text_lengths[f'c{k}']
                text_section_table[k] = None
            elif text_section_table[k] not in ('*', None) and int(text_section_table[k]) == section_idx:
                assert text_lengths[f'c{k}'] <= sections_size[section_idx], f"Not enough space for {k} in section {section_idx:04X}"
                output_fp.write(f'{k}::\n')
                output_fp.write(f'  db #c{k},$00\n')
                sections_size[section_idx] -= text_lengths[f'c{k}']
                text_section_table[k] = None

        output_fp.write('\n')

    assert len([t for t in text_section_table if text_section_table[t] is not None]) == 0, f"Could not fit all text in available sections: {[t for t in text_section_table if text_section_table[t] is not None]} "


    output_fp.write(f'POPC\n')


