; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 16 0", ROMX[$524A], BANK[$43]
CutsceneScript16_0::
  SetPortrait $0B,$10,$00
  Unknown0E $16
  Unknown12 $09
  Unknown02
  Unknown07 $2A,$02,$02,$04,$01,$01,$20,$00
  WriteText "<NAME>くん<BR>おつかれさま。<BR>",$00
  PromptContinue
  WriteText "では ほうこくを<BR>おねがいするわ。<BR>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "はい ほうこくします。<BR>",$00
  PromptContinue
  WriteText "バラぐみの きくちゃんを<BR>たすけました。<BR>",$00
  PromptContinue
  WriteText "きくちゃんは<BR>",CHARACTER_EXT_07,"まじんき・けん",CHARACTER_EXT_08,"を<BR>みつけたそうですが<BR>",$00
  PromptContinue
  WriteText CHARACTER_EXT_07,"まじんき・けん",CHARACTER_EXT_08,"は<BR>なにものかに<BR>もちさられたそうです。<BR>",$00
  PromptContinue
  SetPortrait $0B,$12,$02
  WriteText "そう‥‥<BR>",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"が なにものかに<BR>もちさられたの‥‥‥‥‥‥‥<BR>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "それと ミカサのなかは<BR>こおっている ぶぶんが<BR>あるなど<BR>",$00
  PromptContinue
  WriteText "かなり おかしなことに<BR>なっています。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "わかったわ。<BR>きくちゃんの きゅうじょ<BR>ごくろうさま でした。<BR>",$00
  PromptContinue
  WriteText "<NAME>くんは<BR>つぎの しじがあるまで<BR>やすんでいてちょうだい。<BR>",$00
  PromptContinue
  OptionSelect $02,$00,$D1,$EB,$5E,$8D,$79,$72,$52,$74,$10,$5B,$5D,$00,$00,$98,$95,$54,$59,$52,$00,$01
  Unknown07 $89,$01,$02,$00,$01,$00,$20,$00
  Unknown07 $7B,$01,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText "りょうかい。<BR>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "かえでさん しつもんが<BR>あります。 バラぐみについて<BR>おしえてください。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "バラぐみとは ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>まもるにんむを うけている<BR>ひみつぶたいのことよ。<BR>",$00
  PromptContinue
  WriteText "こんかいは バラぐみも<BR>",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を さがしに<BR>ミカサへ いったみたいね。<BR>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "そうなんですか。<BR>わかりました。<BR>",$00
  PromptContinue
  End
  WriteText "<NAME> おつかれさま。<BR>",$00
  PromptContinue
  WriteText "では ほうこくを<BR>おねがいするわ。<BR>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "はい ほうこくします。<BR>",$00
  PromptContinue
  WriteText "バラぐみの きくちゃんを<BR>たすけました。<BR>",$00
  PromptContinue
  WriteText "きくちゃんは<BR>",CHARACTER_EXT_07,"まじんき・けん",CHARACTER_EXT_08,"を<BR>みつけたそうですが<BR>",$00
  PromptContinue
  WriteText CHARACTER_EXT_07,"まじんき・けん",CHARACTER_EXT_08,"は<BR>なにものかに<BR>もちさられたそうです。<BR>",$00
  PromptContinue
  SetPortrait $0B,$12,$02
  WriteText "そう‥‥<BR>",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"が なにものかに<BR>もちさられたの‥‥‥‥‥‥‥<BR>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "それと ミカサのなかは<BR>こおっている ぶぶんが<BR>あるなど<BR>",$00
  PromptContinue
  WriteText "かなり おかしなことに<BR>なっています。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "わかったわ。<BR>きくちゃんの きゅうじょ<BR>ごくろうさま でした。<BR>",$00
  PromptContinue
  WriteText "<NAME>は<BR>つぎの しじがあるまで<BR>やすんでいてちょうだい。<BR>",$00
  PromptContinue
  OptionSelect $02,$00,$D1,$EB,$5E,$8D,$79,$72,$52,$74,$10,$5B,$5D,$00,$00,$98,$95,$54,$59,$52,$00,$01
  Unknown07 $9D,$03,$02,$00,$01,$00,$20,$00
  Unknown07 $8F,$03,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText "りょうかい。<BR>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "かえでさん しつもんが<BR>あります。 バラぐみについて<BR>おしえてください。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "バラぐみとは ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>まもるにんむを うけている<BR>ひみつぶたいのことよ。<BR>",$00
  PromptContinue
  WriteText "こんかいは バラぐみも<BR>",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を さがしに<BR>ミカサへ いったみたいね。<BR>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "そうなんですか。<BR>わかりました。<BR>",$00
  PromptContinue
  End
  End
CutsceneScript16_0End::


