; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 29 0", ROMX[$6823], BANK[$44]
CutsceneScript29_0::
  Unknown0E $16
  Unknown0F $00,$01
  Unknown12 $17
  Unknown02
  Unknown07 $97,$04,$02,$04,$01,$01,$20,$00
  WriteText $63,$71,$5B,$8D,$72,$5F,$6D,$0D,$D5,$F5,$B0,$7C,$8A,$5D,$76,$54,$FF,$FF,$0D,$00
  Unknown05 $84,$10,$01,$00
  End
  WriteText $8A,$5D,$76,$54,$78,$7C,$79,$10,$D5,$F5,$B0,$59,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $8A,$5D,$76,$54,$75,$10,$D5,$F5,$B0,$76,$5B,$6D,$97,$0D,$63,$5D,$97,$63,$A1,$7C,$76,$61,$9B,$79,$0D,$90,$71,$74,$52,$5D,$65,$59,$78,$52,$78,$9F,$0D,$00
  PromptContinue
  Unknown1E $0C
  WriteText $63,$5D,$97,$63,$A1,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $08,$63,$A1,$0D,$77,$54,$59,$65,$6D,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $61,$A1,$78,$90,$7C,$A0,$10,$8D,$72,$5F,$6D,$7C,$0D,$75,$67,$5A,$FF,$FF,$0D,$63,$5D,$97,$63,$A1,$7C,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $D5,$F5,$B0,$7C,$8A,$5D,$76,$54,$F9,$0D,$50,$71,$10,$6B,$9A,$10,$50,$6D,$65,$7C,$75,$67,$9F,$0D,$00
  PromptContinue
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText $9D,$64,$9D,$64,$10,$67,$8D,$8C,$69,$A1,$9F,$0D,$08,$63,$A1,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $63,$5D,$97,$63,$A1,$10,$8A,$5D,$76,$54,$8C,$75,$0D,$D5,$F5,$B0,$78,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $01,$05,$05
  WriteText $56,$56,$10,$8C,$50,$10,$61,$9A,$6E,$5F,$0D,$78,$A1,$75,$67,$5F,$77,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $76,$61,$9B,$75,$10,$08,$63,$A1,$7D,$0D,$67,$5B,$78,$BA,$DE,$FB,$C5,$76,$59,$0D,$50,$98,$8C,$67,$59,$F9,$0D,$00
  PromptContinue
  OptionSelectTimed $05,$03,$66,$93,$54,$77,$54,$00,$00,$92,$5B,$93,$54,$00,$01,$66,$95,$54,$5B,$10,$66,$77,$54,$65,$91,$EE,$FB,$BA,$00,$02
  Unknown07 $7F,$01,$02,$01,$01,$00,$20,$00
  Unknown07 $5C,$02,$02,$01,$01,$01,$20,$00
  Unknown07 $2A,$03,$02,$01,$01,$02,$20,$00
  Unknown06 $23,$04
  Unknown0F $00,$01
  WriteText $66,$93,$54,$77,$54,$5A,$10,$67,$5B,$75,$67,$9F,$0D,$00
  PromptContinue
  WriteText $79,$89,$A1,$61,$97,$52,$7C,$10,$84,$66,$93,$72,$7D,$0D,$59,$97,$6E,$6E,$5F,$75,$78,$5D,$10,$69,$52,$65,$A1,$90,$0D,$5B,$6D,$56,$8C,$67,$59,$97,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText $6B,$54,$75,$67,$96,$7B,$9F,$0D,$66,$93,$54,$77,$54,$79,$65,$9B,$0D,$5F,$A1,$77,$54,$79,$65,$9B,$0D,$00
  PromptContinue
  WriteText $79,$89,$A1,$61,$97,$52,$7C,$10,$84,$66,$93,$72,$71,$74,$0D,$89,$A1,$76,$54,$79,$10,$52,$52,$75,$67,$96,$7B,$9F,$0D,$00
  PromptContinue
  WriteText $50,$6D,$65,$90,$10,$6F,$6F,$79,$58,$65,$56,$97,$9A,$74,$0D,$67,$67,$A1,$6E,$10,$5F,$A1,$7C,$8D,$6F,$FF,$FF,$0D,$76,$71,$74,$90,$10,$6E,$52,$67,$5B,$78,$A1,$75,$67,$9F,$0D,$00
  PromptContinue
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $92,$5B,$93,$54,$5A,$10,$67,$5B,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText $50,$6D,$65,$90,$10,$67,$5B,$75,$67,$96,$9F,$0D,$8D,$74,$99,$76,$10,$58,$90,$65,$9B,$52,$A1,$0D,$75,$67,$96,$7B,$FC,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $92,$71,$74,$90,$10,$58,$90,$65,$9B,$52,$75,$67,$96,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $6B,$54,$78,$A1,$75,$67,$59,$F9,$0D,$58,$A1,$78,$7C,$10,$50,$6D,$65,$79,$90,$0D,$75,$5B,$8C,$67,$59,$F9,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $90,$6F,$9B,$A1,$75,$67,$96,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $66,$91,$50,$10,$61,$A1,$77,$0D,$58,$65,$56,$74,$5D,$6E,$63,$52,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $66,$95,$54,$5B,$10,$66,$77,$54,$65,$91,$EE,$FB,$BA,$5A,$0D,$67,$5B,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $65,$71,$74,$8C,$67,$96,$9F,$0D,$50,$7C,$10,$7A,$5B,$72,$10,$7A,$59,$9A,$72,$71,$74,$0D,$92,$72,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $6B,$54,$78,$A1,$75,$67,$96,$9F,$0D,$52,$7C,$6F,$A0,$59,$5F,$74,$10,$52,$71,$65,$93,$A1,$7C,$0D,$7D,$A1,$6E,$A1,$75,$10,$59,$5F,$7A,$5F,$99,$9F,$0D,$00
  PromptContinue
  WriteText $B4,$FB,$CB,$FB,$75,$7C,$10,$C8,$C4,$CA,$D3,$FB,$C9,$0D,$78,$A1,$59,$10,$90,$54,$10,$6E,$52,$61,$54,$83,$A1,$0D,$75,$67,$96,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $86,$FC,$10,$6B,$A1,$78,$79,$0D,$58,$90,$65,$9B,$52,$A1,$75,$67,$59,$9F,$0D,$00
  PromptContinue
  WriteText $66,$91,$50,$10,$61,$A1,$77,$0D,$61,$54,$97,$A1,$90,$72,$9A,$74,$10,$52,$71,$65,$95,$79,$0D,$8D,$79,$52,$5B,$8C,$65,$95,$54,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$67,$8D,$8C,$69,$A1,$9F,$0D,$61,$9A,$76,$52,$71,$74,$10,$78,$52,$A1,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$04,$04
  WriteText $6B,$54,$78,$A1,$75,$67,$59,$F9,$0D,$67,$8D,$8C,$69,$A1,$9F,$0D,$86,$A1,$78,$61,$76,$A0,$10,$5B,$52,$74,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  WriteText $63,$71,$5B,$8D,$72,$5F,$6D,$0D,$D5,$F5,$B0,$7C,$8A,$5D,$76,$54,$FF,$FF,$0D,$00
  Unknown05 $84,$10,$01,$00
  End
  WriteText $8A,$5D,$76,$54,$78,$7C,$79,$10,$D5,$F5,$B0,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $8A,$5D,$76,$54,$75,$10,$D5,$F5,$B0,$76,$5B,$6D,$97,$0D,$63,$5D,$97,$63,$A1,$7C,$76,$61,$9B,$79,$0D,$90,$71,$74,$52,$5D,$65,$59,$78,$52,$9D,$7B,$9F,$0D,$00
  PromptContinue
  Unknown1E $0C
  WriteText $63,$5D,$97,$63,$A1,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $08,$63,$A1,$0D,$77,$54,$59,$65,$6D,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $61,$A1,$78,$90,$7C,$A0,$10,$8D,$72,$5F,$6D,$7C,$0D,$75,$67,$5A,$FF,$FF,$0D,$63,$5D,$97,$63,$A1,$7C,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $01,$03,$03
  WriteText $D5,$F5,$B0,$7C,$8A,$5D,$76,$54,$F9,$0D,$50,$71,$10,$6B,$9A,$10,$50,$6D,$65,$7C,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText $9D,$64,$9D,$64,$10,$67,$8D,$8C,$69,$A1,$9F,$0D,$08,$63,$A1,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $8A,$5D,$76,$54,$8C,$75,$10,$D5,$F5,$B0,$6E,$78,$A1,$74,$0D,$63,$5D,$97,$63,$A1,$10,$97,$65,$52,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$05,$05
  WriteText $56,$56,$10,$8C,$50,$10,$61,$9A,$6E,$5F,$0D,$78,$A1,$75,$67,$5F,$77,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $76,$61,$9B,$75,$10,$08,$63,$A1,$7D,$0D,$67,$5B,$78,$BA,$DE,$FB,$C5,$76,$59,$0D,$50,$98,$8C,$67,$59,$F9,$0D,$00
  PromptContinue
  OptionSelectTimed $05,$03,$D6,$A8,$F5,$B8,$F5,$B1,$00,$00,$67,$52,$56,$52,$00,$01,$C7,$CC,$BA,$00,$02
  Unknown07 $06,$06,$02,$01,$01,$00,$20,$00
  Unknown07 $B6,$06,$02,$01,$01,$01,$20,$00
  Unknown07 $85,$07,$02,$01,$01,$02,$20,$00
  Unknown06 $71,$08
  Unknown0F $00,$01
  WriteText $D6,$A8,$F5,$B8,$F5,$B1,$5A,$10,$67,$5B,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $D6,$A8,$F5,$B8,$F5,$B1,$F9,$0D,$50,$50,$10,$69,$52,$96,$54,$7C,$5F,$A1,$77,$54,$0D,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText $50,$6D,$65,$90,$10,$67,$5B,$75,$67,$96,$9F,$0D,$58,$78,$66,$10,$5F,$A1,$7C,$8D,$6F,$0D,$75,$67,$90,$A1,$7B,$9F,$0D,$00
  PromptContinue
  WriteText $75,$90,$10,$D6,$A8,$F5,$B8,$F5,$B1,$6E,$78,$A1,$74,$0D,$08,$63,$A1,$71,$74,$10,$78,$59,$78,$59,$0D,$B8,$E5,$EE,$74,$8C,$67,$7B,$9F,$0D,$00
  PromptContinue
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $67,$52,$56,$52,$5A,$10,$67,$5B,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $67,$8D,$9A,$63,$A1,$92,$10,$EE,$CC,$90,$0D,$67,$52,$56,$52,$10,$67,$5B,$78,$A1,$75,$67,$96,$9F,$0D,$00
  PromptContinue
  WriteText $52,$52,$75,$67,$96,$7B,$FC,$9F,$0D,$58,$96,$5E,$7C,$7D,$10,$6A,$A1,$65,$A1,$7C,$0D,$54,$A1,$77,$54,$79,$10,$78,$98,$8C,$67,$65,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText $78,$79,$96,$98,$90,$10,$8D,$68,$79,$54,$52,$74,$99,$0D,$7C,$71,$74,$10,$5B,$90,$6F,$52,$52,$66,$91,$0D,$78,$52,$75,$67,$59,$9F,$0D,$00
  PromptContinue
  WriteText $7B,$10,$08,$63,$A1,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $56,$56,$10,$6B,$54,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $C7,$CC,$BA,$5A,$10,$67,$5B,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $C7,$CC,$BA,$76,$7D,$10,$78,$59,$78,$59,$0D,$58,$B8,$E5,$EE,$63,$A1,$75,$67,$7B,$9F,$0D,$08,$63,$A1,$7D,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $66,$72,$7D,$C7,$CC,$BA,$71,$74,$0D,$67,$62,$5D,$D0,$FB,$CA,$78,$BA,$DE,$FB,$C5,$0D,$78,$A1,$75,$67,$96,$9F,$0D,$00
  PromptContinue
  WriteText $66,$6B,$5D,$13,$11,$11,$AE,$EF,$75,$0D,$76,$A1,$75,$5D,$99,$DD,$FB,$ED,$A0,$0D,$54,$6F,$50,$54,$A1,$75,$67,$59,$97,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$03,$03
  WriteText $A9,$A9,$C4,$FA,$0D,$6B,$54,$78,$A1,$75,$67,$59,$FA,$F9,$0D,$00
  PromptContinue
  WriteText $6B,$9A,$7D,$10,$BA,$B5,$A5,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText $6B,$9A,$A0,$92,$71,$74,$52,$99,$0D,$08,$63,$A1,$90,$10,$0D,$BA,$B5,$A5,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$67,$8D,$8C,$69,$A1,$9F,$0D,$61,$9A,$76,$52,$71,$74,$10,$78,$52,$A1,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $01,$04,$04
  WriteText $6B,$54,$78,$A1,$75,$67,$59,$F9,$0D,$67,$8D,$8C,$69,$A1,$9F,$0D,$86,$A1,$78,$61,$76,$A0,$10,$5B,$52,$74,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $6B,$9A,$66,$91,$10,$08,$63,$A1,$0D,$9D,$64,$9D,$64,$10,$76,$77,$5F,$74,$5D,$6E,$63,$71,$74,$0D,$50,$98,$5A,$76,$54,$62,$64,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  End
  End
CutsceneScript29_0End::


