; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 47 0", ROMX[$7283], BANK[$4B]
CutsceneScript47_0::
  SetPortrait $08,$00,$00
  Unknown0E $20
  Unknown12 $04
  Unknown02
  WriteText "ボクはレニ‥‥<br>",$00
  PromptContinue
  WriteText "ボクのせんじょうでのやくめは<br>ぜんえいで すばやく<br>てきを はかいすること。<br>",$00
  PromptContinue
  WriteText "スピードこそが<br>しょうはいを さゆうする。<br>",$00
  PromptContinue
  WriteText "せんじょうにおいて<br>たいせつなこと それは<br>かつこと それだけ。<br>",$00
  PromptContinue
  WriteText "じゃあ<br>がんばれ‥‥<br>",$00
  PromptContinue
  End
  End
CutsceneScript47_0End::


