; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 42 0", ROMX[$6F48], BANK[$4B]
CutsceneScript42_0::
  RSRESET
  SetPortrait $03,$00,$00
  Unknown0E $0E
  Unknown12 $04
  Unknown02
  WriteText "ようこそ<BR>ていこくかげきだんへ。<BR>マリア・タチバナです。<BR>",$00
  PromptContinue
  WriteText "わたしのぶきは じゅうです。<BR>しゃげきで はなれたてきも<BR>こうげきすることができます。<BR>",$00
  PromptContinue
  WriteText "せんじょうでは<BR>ちいさなゆだんが<BR>はいぼくに つながるわ。<BR>",$00
  PromptContinue
  WriteText "きをひきしめて<BR>しっかりと<BR>がんばりなさい。<BR>",$00
  PromptContinue
  End
  End
CutsceneScript42_0End::


