; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 4F 0", ROMX[$782F], BANK[$4B]
CutsceneScript4F_0::
  SetPortrait $0B,$10,$00
  Unknown0E $16
  Unknown12 $16
  Unknown02
  Unknown07 $B9,$00,$02,$04,$01,$01,$20,$00
  WriteText $08,$5D,$A1,$0D,$58,$72,$59,$9A,$63,$8C,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$14,$04
  WriteText $94,$71,$5D,$98,$92,$67,$A1,$75,$0D,$6F,$95,$54,$6E,$52,$FF,$FF,$76,$0D,$52,$52,$6D,$52,$76,$61,$9B,$10,$6E,$5F,$77,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $9A,$A1,$97,$5D,$5A,$10,$76,$9A,$78,$5D,$78,$71,$6D,$0D,$AC,$F5,$CB,$76,$A3,$A5,$EC,$BA,$5A,$0D,$65,$A1,$7F,$52,$6E,$9D,$9F,$0D,$00
  PromptContinue
  WriteText $52,$71,$61,$5D,$90,$7D,$92,$5D,$0D,$83,$6D,$98,$A0,$10,$8D,$72,$5F,$74,$0D,$6F,$95,$54,$6E,$52,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $6B,$9A,$8C,$75,$10,$89,$59,$7C,$A9,$EC,$A3,$7C,$0D,$6D,$A1,$63,$5D,$7D,$10,$6F,$93,$54,$65,$96,$9F,$0D,$00
  PromptContinue
  WriteText $9D,$59,$71,$6D,$9D,$7B,$0D,$08,$5D,$A1,$9F,$0D,$00
  PromptContinue
  End
  WriteText $08,$10,$58,$72,$59,$9A,$63,$8C,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$14,$04
  WriteText $94,$71,$5D,$98,$92,$67,$A1,$75,$0D,$6F,$95,$54,$6E,$52,$FF,$FF,$76,$0D,$52,$52,$6D,$52,$76,$61,$9B,$10,$6E,$5F,$77,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $9A,$A1,$97,$5D,$5A,$10,$76,$9A,$78,$5D,$78,$71,$6D,$0D,$AC,$F5,$CB,$76,$A3,$A5,$EC,$BA,$5A,$0D,$65,$A1,$7F,$52,$6E,$9D,$9F,$0D,$00
  PromptContinue
  WriteText $52,$71,$61,$5D,$90,$7D,$92,$5D,$0D,$83,$6D,$98,$A0,$10,$8D,$72,$5F,$74,$0D,$6F,$95,$54,$6E,$52,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $6B,$9A,$8C,$75,$10,$89,$59,$7C,$A9,$EC,$A3,$7C,$0D,$6D,$A1,$63,$5D,$7D,$10,$6F,$93,$54,$65,$96,$9F,$0D,$00
  PromptContinue
  WriteText $9D,$59,$71,$6D,$9D,$7B,$10,$08,$9F,$0D,$00
  PromptContinue
  End
  End
CutsceneScript4F_0End::


