; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 29 0", ROMX[$6823], BANK[$44]
CutsceneScript29_0::
  Unknown0E $16
  Unknown0F $00,$01
  Unknown12 $17
  Unknown02
  Unknown07 $97,$04,$02,$04,$01,$01,$20,$00
  WriteText "さっきみつけた<br>ピンクのぼくとう‥‥<br>",$00
  Unknown05 $84,$10,$01,$00
  End
  WriteText "ぼくとうなのに ピンクか‥‥<br>",$00
  PromptContinue
  WriteText "ぼくとうで ピンクときたら<br>さくらさんのところに<br>もっていくしかないな。<br>",$00
  PromptContinue
  Unknown1E $0C
  WriteText "さくらさん。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $08,"さん<br>どうかしたんですか?<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "こんなものを みつけたの<br>ですが‥‥<br>さくらさんのですか?<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "ピンクのぼくとう?<br>あっ それ あたしのです。<br>",$00
  PromptContinue
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText "わざわざ すみません。<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "さくらさん ぼくとうまで<br>ピンクなんですか?<br>",$00
  PromptContinue
  SetPortrait $01,$05,$05
  WriteText "ええ まあ これだけ<br>なんですけどね。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "ところで ",$08,"さんは<br>すきなスポーツとか<br>ありますか?<br>",$00
  PromptContinue
  OptionSelectTimed $05,$03,$66,$93,$54,$77,$54,$00,$00,$92,$5B,$93,$54,$00,$01,$66,$95,$54,$5B,$10,$66,$77,$54,$65,$91,$EE,$FB,$BA,$00,$02
  Unknown07 $7F,$01,$02,$01,$01,$00,$20,$00
  Unknown07 $5C,$02,$02,$01,$01,$01,$20,$00
  Unknown07 $2A,$03,$02,$01,$01,$02,$20,$00
  Unknown06 $23,$04
  Unknown0F $00,$01
  WriteText "じゅうどうが すきです。<br>",$00
  PromptContinue
  WriteText "にほんこらいの ぶじゅつは<br>からだだけでなく せいしんも<br>きたえますからね。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText "そうですよね。<br>じゅうどうにしろ<br>けんどうにしろ<br>",$00
  PromptContinue
  WriteText "にほんこらいの ぶじゅつって<br>ほんとうに いいですよね。<br>",$00
  PromptContinue
  WriteText "あたしも ちちにおしえられて<br>すすんだ けんのみち‥‥<br>とっても だいすきなんです。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "やきゅうが すきです。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText "あたしも すきですよ。<br>みてると おもしろいん<br>ですよね～。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "やっても おもしろいですよ。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "そうなんですか?<br>おんなの あたしにも<br>できますか?<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "もちろんですよ。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "じゃあ こんど<br>おしえてくださいね。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "じょうき じどうしゃレースが<br>すきです。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "しってますよ。<br>あの ぬきつ ぬかれつって<br>やつですね。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "そうなんですよ。<br>いのちをかけて いっしゅんの<br>はんだんで かけぬける。<br>",$00
  PromptContinue
  WriteText "コーナーでの デッドヒート<br>なんか もう だいこうふん<br>ですよ。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "へ～ そんなに<br>おもしろいんですか。<br>",$00
  PromptContinue
  WriteText "じゃあ こんど<br>こうらんもつれて いっしょに<br>みにいきましょう。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "‥‥‥‥‥‥‥‥すみません。<br>これといって ないんです。<br>",$00
  PromptContinue
  SetPortrait $01,$04,$04
  WriteText "そうなんですか?<br>すみません。<br>へんなことを きいて‥‥<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  WriteText "さっきみつけた<br>ピンクのぼくとう‥‥<br>",$00
  Unknown05 $84,$10,$01,$00
  End
  WriteText "ぼくとうなのに ピンク‥‥<br>",$00
  PromptContinue
  WriteText "ぼくとうで ピンクときたら<br>さくらさんのところに<br>もっていくしかないわね。<br>",$00
  PromptContinue
  Unknown1E $0C
  WriteText "さくらさん。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText $08,"さん<br>どうかしたんですか?<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "こんなものを みつけたの<br>ですが‥‥<br>さくらさんのですか?<br>",$00
  PromptContinue
  SetPortrait $01,$03,$03
  WriteText "ピンクのぼくとう?<br>あっ それ あたしのです。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText "わざわざ すみません。<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "ぼくとうまで ピンクだなんて<br>さくらさん らしいですね。<br>",$00
  PromptContinue
  SetPortrait $01,$05,$05
  WriteText "ええ まあ これだけ<br>なんですけどね。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "ところで ",$08,"さんは<br>すきなスポーツとか<br>ありますか?<br>",$00
  PromptContinue
  OptionSelectTimed $05,$03,$D6,$A8,$F5,$B8,$F5,$B1,$00,$00,$67,$52,$56,$52,$00,$01,$C7,$CC,$BA,$00,$02
  Unknown07 $06,$06,$02,$01,$01,$00,$20,$00
  Unknown07 $B6,$06,$02,$01,$01,$01,$20,$00
  Unknown07 $85,$07,$02,$01,$01,$02,$20,$00
  Unknown06 $71,$08
  Unknown0F $00,$01
  WriteText "フェンシングが すきです。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "フェンシング?<br>ああ せいようのけんどう<br>ですね。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText "あたしも すきですよ。<br>おなじ けんのみち<br>ですもんね。<br>",$00
  PromptContinue
  WriteText "でも フェンシングだなんて<br>",$08,"さんって なかなか<br>シャレてますね。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "すいえいが すきです。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "すみれさんや レニも<br>すいえい すきなんですよ。<br>",$00
  PromptContinue
  WriteText "いいですよね～。<br>およぐのは ぜんしんの<br>うんどうに なりますし。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText "なによりも みずにういてる<br>のって きもちいいじゃ<br>ないですか。<br>",$00
  PromptContinue
  WriteText "ね ",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "ええ そうですね。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "テニスが すきです。<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "テニスとは なかなか<br>おシャレさんですね。<br>",$08,"さんは。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "じつはテニスって<br>すごくハードなスポーツ<br>なんですよ。<br>",$00
  PromptContinue
  WriteText "じそく200キロで<br>とんでくるボールを<br>うちあうんですから。<br>",$00
  PromptContinue
  SetPortrait $01,$03,$03
  WriteText "エエッ!<br>そうなんですか!?<br>",$00
  PromptContinue
  WriteText "それは スゴイですね。<br>",$00
  PromptContinue
  Unknown1A $40,$91,$03,$91,$01,$06,$28,$00
  WriteText "それをやっている<br>",$08,"さんも <br>スゴイです。<br>",$00
  PromptContinue
  SetPortrait $01,$01,$01
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "‥‥‥‥‥‥‥‥すみません。<br>これといって ないんです。<br>",$00
  PromptContinue
  SetPortrait $01,$04,$04
  WriteText "そうなんですか?<br>すみません。<br>へんなことを きいて‥‥<br>",$00
  PromptContinue
  SetPortrait $01,$00,$00
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくださって<br>ありがとうございました。<br>",$00
  PromptContinue
  End
  End
CutsceneScript29_0End::


