; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 4C 0", ROMX[$7590], BANK[$4B]
CutsceneScript4C_0::
  SetPortrait $0E,$11,$01
  Unknown0E $16
  Unknown12 $04
  Unknown02
  WriteText "こんにちわ!<BR>あたし たかむら つばき<BR>っていいます。<BR>",$00
  PromptContinue
  SetPortrait $0E,$10,$00
  WriteText "かすみさんや ゆりさんと<BR>いっしょに あなたの<BR>サポートを やりますから<BR>",$00
  PromptContinue
  WriteText "わからないことがあったら<BR>いつでも つうしんで<BR>れんらくください!<BR>",$00
  PromptContinue
  SetPortrait $0E,$11,$01
  WriteText "おうえんしてますからね!<BR>ファイト! ファイト!<BR>がんばってくださいね!<BR>",$00
  PromptContinue
  End
  End
CutsceneScript4C_0End::


