; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 53 0", ROMX[$5910], BANK[$4C]
CutsceneScript53_0::
  Unknown0E $1A
  Unknown0F $00,$01
  Unknown0D $05,$20
  Unknown12 $05
  Unknown02
  Unknown07 $E6,$01,$02,$04,$01,$01,$20,$00
  WriteText $61,$54,$97,$A1,$63,$A1,$9F,$0D,$6F,$95,$71,$76,$10,$52,$52,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $A1,$FC,$FC,$78,$A1,$92,$9F,$0D,$08,$7D,$A1,$10,$59,$52,$78,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $66,$72,$7D,$10,$61,$A1,$78,$E4,$CF,$A0,$0D,$80,$9B,$71,$6D,$7C,$10,$75,$67,$5A,$FF,$FF,$0D,$8D,$74,$90,$97,$56,$8C,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$22,$12
  WriteText $78,$A1,$92,$10,$56,$97,$5D,$75,$59,$52,$0D,$52,$65,$61,$9B,$92,$78,$FC,$9F,$0D,$77,$9A,$77,$9A,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $05,$23,$13
  WriteText $50,$71,$FA,$FA,$10,$61,$9A,$7D,$FA,$FA,$0D,$A7,$FB,$C5,$61,$54,$10,$92,$78,$52,$59,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$21,$11
  WriteText $08,$7D,$A1,$9F,$0D,$A9,$A9,$90,$A1,$10,$80,$9B,$71,$74,$5B,$6D,$78,$FC,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $6B,$FF,$6B,$A1,$78,$BA,$B5,$A5,$10,$52,$65,$61,$9B,$0D,$78,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $69,$92,$9F,$A7,$FB,$C5,$61,$54,$71,$74,$52,$54,$7C,$7D,$0D,$B6,$D4,$78,$52,$10,$8C,$5A,$97,$78,$52,$0D,$6B,$65,$74,$10,$65,$78,$92,$59,$78,$10,$74,$72,$9F,$0D,$00
  PromptContinue
  WriteText $72,$8C,$98,$10,$59,$6D,$78,$A0,$10,$72,$5D,$99,$7C,$79,$0D,$54,$71,$74,$72,$5F,$7C,$0D,$61,$54,$69,$5B,$78,$A1,$92,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $65,$59,$90,$10,$61,$9A,$75,$72,$5D,$97,$9A,$6D,$0D,$5F,$A1,$7D,$01,$07,$C1,$DF,$BA,$AC,$BA,$7C,$6D,$6F,$01,$08,$0D,$52,$54,$74,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $92,$52,$7E,$7C,$10,$80,$95,$54,$8F,$A1,$79,$0D,$78,$5A,$9A,$99,$10,$8D,$68,$7C,$96,$54,$78,$0D,$90,$A1,$96,$54,$5A,$10,$50,$97,$9D,$9A,$99,$A1,$92,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $78,$A1,$6E,$59,$10,$BA,$B5,$A5,$75,$67,$7B,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $6B,$92,$9B,$FC,$F9,$0D,$00
  PromptContinue
  WriteText $72,$5C,$7C,$10,$65,$93,$72,$60,$5B,$8C,$75,$79,$7D,$0D,$D1,$C4,$C2,$EC,$10,$72,$5D,$71,$76,$5D,$59,$97,$0D,$6D,$7C,$65,$8D,$79,$10,$8C,$71,$76,$71,$74,$92,$9F,$0D,$00
  PromptContinue
  WriteText $89,$78,$10,$8C,$6D,$78,$9F,$0D,$00
  PromptContinue
  Unknown0D $00,$00
  Unknown0F $00,$01
  Unknown09 $64
  End
  WriteText $61,$54,$97,$A1,$63,$A1,$9F,$0D,$6F,$95,$71,$76,$10,$52,$52,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $A1,$FC,$FC,$78,$A1,$92,$9F,$0D,$08,$7D,$A1,$10,$59,$52,$78,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $66,$72,$7D,$10,$61,$A1,$78,$E4,$CF,$A0,$0D,$80,$9B,$71,$6D,$7C,$10,$75,$67,$5A,$FF,$FF,$0D,$8D,$74,$90,$97,$56,$8C,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$22,$12
  WriteText $78,$A1,$92,$10,$56,$97,$5D,$75,$59,$52,$0D,$52,$65,$61,$9B,$92,$78,$FC,$9F,$0D,$77,$9A,$77,$9A,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $05,$23,$13
  WriteText $50,$71,$FA,$FA,$10,$61,$9A,$7D,$FA,$FA,$0D,$A7,$FB,$C5,$61,$54,$10,$92,$78,$52,$59,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$21,$11
  WriteText $08,$7D,$A1,$9F,$0D,$A9,$A9,$90,$A1,$10,$80,$9B,$71,$74,$5B,$6D,$78,$FC,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $6B,$FF,$6B,$A1,$78,$BA,$B5,$A5,$10,$52,$65,$61,$9B,$0D,$78,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $69,$92,$9F,$A7,$FB,$C5,$61,$54,$71,$74,$52,$54,$7C,$7D,$0D,$B6,$D4,$78,$52,$10,$8C,$5A,$97,$78,$52,$0D,$6B,$65,$74,$10,$65,$78,$92,$59,$78,$10,$74,$72,$9F,$0D,$00
  PromptContinue
  WriteText $72,$8C,$98,$10,$59,$6D,$78,$A0,$10,$72,$5D,$99,$7C,$79,$0D,$54,$71,$74,$72,$5F,$7C,$0D,$61,$54,$69,$5B,$78,$A1,$92,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $65,$59,$90,$10,$61,$9A,$75,$72,$5D,$97,$9A,$6D,$0D,$5F,$A1,$7D,$01,$07,$C1,$DF,$BA,$AC,$BA,$7C,$6D,$6F,$01,$08,$0D,$52,$54,$74,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $92,$52,$7E,$7C,$10,$80,$95,$54,$8F,$A1,$79,$0D,$78,$5A,$9A,$99,$10,$8D,$68,$7C,$96,$54,$78,$0D,$90,$A1,$96,$54,$5A,$10,$50,$97,$9D,$9A,$99,$A1,$92,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $78,$A1,$6E,$59,$10,$BA,$B5,$A5,$75,$67,$7B,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $6B,$92,$9B,$FC,$F9,$0D,$00
  PromptContinue
  WriteText $72,$5C,$7C,$10,$65,$93,$72,$60,$5B,$8C,$75,$79,$7D,$0D,$D1,$C4,$C2,$EC,$10,$72,$5D,$71,$76,$5D,$59,$97,$0D,$6D,$7C,$65,$8D,$79,$10,$8C,$71,$76,$71,$74,$92,$9F,$0D,$00
  PromptContinue
  WriteText $89,$78,$10,$8C,$6D,$78,$9F,$0D,$00
  PromptContinue
  Unknown0D $00,$00
  Unknown0F $00,$01
  Unknown09 $64
  End
  End
CutsceneScript53_0End::


