; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 1B 0", ROMX[$6B08], BANK[$43]
CutsceneScript1B_0::
  SetPortrait $0B,$11,$01
  Unknown0E $16
  Unknown12 $09
  Unknown02
  Unknown07 $EF,$01,$02,$04,$01,$01,$20,$00
  WriteText $58,$59,$56,$98,$78,$63,$52,$9F,$0D,$08,$5D,$A1,$9F,$0D,$00
  PromptContinue
  WriteText $AC,$F5,$CB,$76,$A3,$A5,$EC,$BA,$7C,$0D,$5B,$93,$54,$65,$93,$72,$0D,$62,$5D,$9B,$54,$63,$8C,$75,$65,$6D,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $75,$7D,$10,$89,$54,$61,$5D,$A0,$0D,$58,$7B,$5A,$52,$67,$99,$9D,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $7D,$52,$10,$89,$54,$61,$5D,$65,$8C,$67,$9F,$0D,$00
  PromptContinue
  WriteText $7C,$61,$98,$13,$72,$7C,$01,$07,$8C,$66,$A1,$5B,$01,$08,$7D,$0D,$E0,$AC,$B6,$79,$7D,$0D,$50,$98,$8C,$69,$A1,$75,$65,$6D,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $6B,$54,$FF,$FF,$0D,$E0,$AC,$B6,$79,$7D,$10,$78,$59,$71,$6D,$7C,$7B,$FF,$FF,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $6B,$9A,$76,$10,$E0,$AC,$B6,$79,$0D,$58,$58,$5B,$78,$10,$50,$78,$5A,$50,$5B,$0D,$6B,$7C,$65,$6D,$79,$7D,$0D,$00
  PromptContinue
  WriteText $01,$07,$92,$8C,$76,$01,$08,$76,$10,$96,$7E,$9A,$74,$52,$99,$0D,$6E,$52,$6F,$5A,$10,$8D,$56,$74,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$12,$02
  WriteText $9D,$59,$98,$8C,$65,$6D,$9F,$0D,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $75,$7D,$10,$08,$5D,$A1,$7D,$0D,$72,$5C,$7C,$10,$65,$66,$5A,$50,$99,$8C,$75,$0D,$92,$67,$A1,$75,$52,$74,$6F,$95,$54,$6E,$52,$9F,$0D,$00
  PromptContinue
  OptionSelect $02,$00,$01,$07,$92,$8C,$76,$01,$08,$79,$72,$52,$74,$10,$5B,$5D,$00,$00,$98,$95,$54,$59,$52,$00,$01
  Unknown07 $6D,$01,$02,$00,$01,$00,$20,$00
  Unknown07 $5F,$01,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText $98,$95,$54,$59,$52,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $59,$56,$75,$63,$A1,$10,$65,$72,$90,$A1,$5A,$0D,$50,$98,$8C,$67,$9F,$10,$01,$07,$92,$8C,$76,$01,$08,$79,$0D,$72,$52,$74,$10,$58,$65,$56,$74,$5D,$6E,$63,$52,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $01,$07,$92,$8C,$76,$01,$08,$76,$7D,$10,$6B,$7C,$8E,$59,$65,$0D,$54,$8D,$7C,$6B,$61,$79,$10,$83,$54,$52,$A1,$63,$9A,$6D,$0D,$7C,$9B,$9D,$9A,$6D,$10,$6E,$52,$6F,$96,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $7C,$9B,$9D,$9A,$6D,$10,$6E,$52,$6F,$FF,$FF,$0D,$78,$A1,$6E,$59,$10,$92,$7E,$6B,$54,$6E,$6C,$FF,$FF,$0D,$00
  PromptContinue
  End
  WriteText $58,$59,$56,$98,$78,$63,$52,$9F,$0D,$08,$9F,$0D,$00
  PromptContinue
  WriteText $AC,$F5,$CB,$76,$A3,$A5,$EC,$BA,$7C,$0D,$5B,$93,$54,$65,$93,$72,$0D,$62,$5D,$9B,$54,$63,$8C,$75,$65,$6D,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $75,$7D,$10,$89,$54,$61,$5D,$A0,$0D,$58,$7B,$5A,$52,$67,$99,$9D,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $7D,$52,$10,$89,$54,$61,$5D,$65,$8C,$67,$9F,$0D,$00
  PromptContinue
  WriteText $7C,$61,$98,$13,$72,$7C,$01,$07,$8C,$66,$A1,$5B,$01,$08,$7D,$0D,$E0,$AC,$B6,$79,$7D,$0D,$50,$98,$8C,$69,$A1,$75,$65,$6D,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $6B,$54,$FF,$FF,$0D,$E0,$AC,$B6,$79,$7D,$10,$78,$59,$71,$6D,$7C,$7B,$FF,$FF,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $6B,$9A,$76,$10,$E0,$AC,$B6,$79,$0D,$58,$58,$5B,$78,$10,$50,$78,$5A,$50,$5B,$0D,$6B,$7C,$65,$6D,$79,$7D,$0D,$00
  PromptContinue
  WriteText $01,$07,$92,$8C,$76,$01,$08,$76,$10,$96,$7E,$9A,$74,$52,$99,$0D,$6E,$52,$6F,$5A,$10,$8D,$56,$74,$52,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$12,$02
  WriteText $9D,$59,$98,$8C,$65,$6D,$9F,$0D,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $75,$7D,$10,$08,$7D,$0D,$72,$5C,$7C,$10,$65,$66,$5A,$50,$99,$8C,$75,$0D,$92,$67,$A1,$75,$52,$74,$6F,$95,$54,$6E,$52,$9F,$0D,$00
  PromptContinue
  OptionSelect $02,$00,$01,$07,$92,$8C,$76,$01,$08,$79,$72,$52,$74,$10,$5B,$5D,$00,$00,$98,$95,$54,$59,$52,$00,$01
  Unknown07 $46,$03,$02,$00,$01,$00,$20,$00
  Unknown07 $38,$03,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText $98,$95,$54,$59,$52,$9F,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $59,$56,$75,$63,$A1,$10,$65,$72,$90,$A1,$5A,$0D,$50,$98,$8C,$67,$9F,$10,$01,$07,$92,$8C,$76,$01,$08,$79,$0D,$72,$52,$74,$10,$58,$65,$56,$74,$5D,$6E,$63,$52,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $01,$07,$92,$8C,$76,$01,$08,$76,$7D,$10,$6B,$7C,$8E,$59,$65,$0D,$54,$8D,$7C,$6B,$61,$79,$10,$83,$54,$52,$A1,$63,$9A,$6D,$0D,$7C,$9B,$9D,$9A,$6D,$10,$6E,$52,$6F,$96,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $7C,$9B,$9D,$9A,$6D,$10,$6E,$52,$6F,$FF,$FF,$0D,$61,$9D,$6B,$54,$6E,$9D,$FF,$FF,$0D,$00
  PromptContinue
  End
  End
CutsceneScript1B_0End::


