; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 55 0", ROMX[$680A], BANK[$4C]
CutsceneScript55_0::
  SetPortrait $06,$10,$08
  Unknown0E $16
  Unknown12 $04
  Unknown02
  Unknown07 $A9,$05,$02,$04,$01,$01,$20,$00
  WriteText "よう ",$08,"!<br>つぎの しゅつげきばしょは<br>ミカサ つうきこうだ。<br>",$00
  PromptContinue
  WriteText "こんかい ",$08,"と<br>いっしょに しゅつげき<br>できるのは<br>",$00
  PromptContinue
  SetPortrait $06,$11,$09
  WriteText "あたいと<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "わたしと<br>",$00
  PromptContinue
  SetPortrait $08,$10,$08
  WriteText "ボクだ。<br>",$00
  PromptContinue
  SetPortrait $06,$10,$08
  WriteText "じゃあ それぞれの<br>とくいわざを ",$08,"に<br>おしえておくぜ。<br>",$00
  PromptContinue
  WriteText "あたいの とくいわざは<br>カラテだ。せっきんせんなら<br>まかしといてくれよ。<br>",$00
  PromptContinue
  WriteText "ちかくにいる てきしか<br>こうげきできないけど<br>はかいりょくは すげぇぜ!<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "わたしは れいりょくを<br>つかった こうげきが<br>とくいでーす。<br>",$00
  PromptContinue
  WriteText "れいりょくのビームで<br>とおくにいる てきにも<br>こうげきできまーす。<br>",$00
  PromptContinue
  WriteText "しかも ふくすうのてきに<br>いちどで こうげきすることも<br>できるのでーす。<br>",$00
  PromptContinue
  SetPortrait $08,$10,$08
  WriteText "ボクのぶきは ランス‥‥<br>つまり ヤリだ。<br>",$00
  PromptContinue
  WriteText "つうじょうは<br>いったいのてきに たいしての<br>こうげきだけど‥‥<br>",$00
  PromptContinue
  WriteText "れいりょくを つかえば<br>ふくすうのてきを<br>こうげきすることができる。<br>",$00
  PromptContinue
  SetPortrait $06,$10,$08
  WriteText "てな かんじだな。<br>",$00
  PromptContinue
  WriteText "じぶんの そうびと<br>パートナーの のうりょくを<br>よくかんがえて<br>",$00
  PromptContinue
  WriteText "バランスのとれた<br>チームをくめば せんとうが<br>ゆうりになるぜ。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ところで ",$08,"さんは<br>せんとうちゅうに ぶきを<br>もちかえてまーすか?<br>",$00
  PromptContinue
  OptionSelect $02,$00,$7D,$52,$00,$00,$52,$52,$56,$00,$01
  Unknown07 $61,$02,$02,$00,$01,$00,$20,$00
  Unknown07 $1E,$03,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText "はい。<br>もちかえています。<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  Unknown1A $40,$97,$03,$97,$01,$06,$28,$00
  WriteText "さすがは ",$08,"さん。<br>やりまーすね。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ぶきの もちかえには<br>1ターン しょうひしますが<br>",$00
  PromptContinue
  WriteText "それぞれの ぶきに<br>ぞくせいのちがう わざを<br>セットしておくと<br>",$00
  PromptContinue
  WriteText "どんなてきが あらわれても<br>ぶきを もちかえるだけで<br>らくに たたかえて<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  WriteText "とーーっても<br>べんりですからね!!<br>",$00
  PromptContinue
  Unknown06 $01,$04
  Unknown0F $00,$01
  WriteText "いいえ。<br>せんとうちゅうの ぶきの<br>もちかえは していません。<br>",$00
  PromptContinue
  SetPortrait $07,$17,$10
  WriteText "Oh! そうなんですか?!<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ぶきの もちかえには<br>1ターンしょうひしますが<br>けっこう べんりなのでーす。<br>",$00
  PromptContinue
  SetPortrait $08,$10,$08
  WriteText "それぞれの ぶきに<br>ぞくせいのちがう わざを<br>セットしておくと<br>",$00
  PromptContinue
  WriteText "どんなてきが あらわれても<br>ぶきを もちかえるだけで<br>らくに たたかえる。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "そのとおりでーす。<br>",$08,"さんも いちど<br>つかってみてくださーい。<br>",$00
  PromptContinue
  Unknown06 $01,$04
  SetPortrait $06,$10,$08
  WriteText "それじゃあ ",$08,"<br>じゅんびは いいか?<br>",$00
  PromptContinue
  OptionSelect $02,$00,$84,$5B,$7C,$90,$6F,$59,$56,$79,$72,$52,$74,$10,$5B,$5D,$00,$00,$D1,$C4,$C2,$EC,$75,$67,$00,$01
  Unknown07 $48,$04,$02,$00,$01,$00,$20,$00
  Unknown07 $54,$05,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText "すみません。<br>ぶきの もちかえについて<br>もういちど おねがいします。<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  WriteText "わかりました。<br>ぶきの もちかえについて<br>でーすね。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ぶきは せんとうちゅうに<br>もちかえることが<br>できるのでーす。<br>",$00
  PromptContinue
  WriteText "ぶきの もちかえには<br>1ターンつかって<br>しまうのでーす。<br>",$00
  PromptContinue
  WriteText "でも かんがえて つかうと<br>とても ベンリで グッドな<br>ものなのでーす。<br>",$00
  PromptContinue
  WriteText "それぞれの ぶきに<br>ぞくせいのちがう わざを<br>セットしておけば<br>",$00
  PromptContinue
  WriteText "どんなてきが あらわれても<br>ぶきを もちかえるだけで<br>らくに たたかえるのでーす。<br>",$00
  PromptContinue
  Unknown06 $01,$04
  Unknown0F $00,$01
  WriteText "はい バッチリです。<br>",$00
  PromptContinue
  SetPortrait $06,$11,$09
  WriteText "それじゃあ ",$08,"!<br>がんばっていこうぜ!!<br>",$00
  PromptContinue
  SetPortrait $08,$10,$08
  WriteText "しっかり‥‥<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  WriteText $08,"さん<br>レッツ ファイトでーす!!<br>",$00
  PromptContinue
  End
  WriteText "よう ",$08,"!<br>つぎの しゅつげきばしょは<br>ミカサ つうきこうだ。<br>",$00
  PromptContinue
  WriteText "こんかい ",$08,"と<br>いっしょに しゅつげき<br>できるのは<br>",$00
  PromptContinue
  SetPortrait $06,$11,$09
  WriteText "あたいと<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "わたしと<br>",$00
  PromptContinue
  SetPortrait $02,$10,$08
  WriteText "そして‥‥<br>わたくしですわ。<br>",$00
  PromptContinue
  SetPortrait $06,$10,$08
  WriteText "それじゃあ それぞれの<br>とくいわざを ",$08,"に<br>おしえておくぜ。<br>",$00
  PromptContinue
  WriteText "あたいの とくいわざは<br>カラテだ。せっきんせんなら<br>まかしといてくれよ。<br>",$00
  PromptContinue
  WriteText "ちかくにいる てきしか<br>こうげきできないけど<br>はかいりょくは すげぇぜ!<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "わたしは れいりょくを<br>つかった こうげきが<br>とくいでーす。<br>",$00
  PromptContinue
  WriteText "れいりょくのビームで<br>とおくにいる てきにも<br>こうげきできまーす。<br>",$00
  PromptContinue
  WriteText "しかも ふくすうのてきに<br>いちどで こうげきすることも<br>できるのでーす。<br>",$00
  PromptContinue
  SetPortrait $02,$10,$08
  WriteText "わたくしの とくぎは<br>なぎなた ですわ!<br>",$00
  PromptContinue
  WriteText "てきが どんなじんけいで<br>あらわれても なぎなたの<br>ながさを いかして<br>",$00
  PromptContinue
  WriteText "ぜんたいを こうげきしたり<br>ならんでるてきを くしざしに<br>したりと‥‥<br>",$00
  PromptContinue
  WriteText "かれいに うつくしく<br>たたかうのが わたくし<br>かんざきすみれ なのですわ。<br>",$00
  PromptContinue
  SetPortrait $06,$10,$08
  WriteText "てな かんじだな。<br>",$00
  PromptContinue
  WriteText "じぶんの そうびと<br>パートナーの のうりょくを<br>よくかんがえて<br>",$00
  PromptContinue
  WriteText "バランスのとれた<br>チームをくめば せんとうが<br>ゆうりになるぜ。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ところで ",$08,"さんは<br>せんとうちゅうに ぶきを<br>もちかえてまーすか?<br>",$00
  PromptContinue
  OptionSelect $02,$00,$7D,$52,$00,$00,$52,$52,$56,$00,$01
  Unknown07 $31,$08,$02,$00,$01,$00,$20,$00
  Unknown07 $EE,$08,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText "はい。<br>もちかえています。<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  Unknown1A $40,$97,$03,$97,$01,$06,$28,$00
  WriteText "さすがは ",$08,"さん。<br>やりまーすね。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ぶきの もちかえには<br>1ターン しょうひしますが<br>",$00
  PromptContinue
  WriteText "それぞれの ぶきに<br>ぞくせいのちがう わざを<br>セットしておくと<br>",$00
  PromptContinue
  WriteText "どんなてきが あらわれても<br>ぶきを もちかえるだけで<br>らくに たたかえて<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  WriteText "とーーっても<br>べんりですからね!!<br>",$00
  PromptContinue
  Unknown06 $D6,$09
  Unknown0F $00,$01
  WriteText "いいえ。<br>せんとうちゅうの ぶきの<br>もちかえは していません。<br>",$00
  PromptContinue
  SetPortrait $07,$17,$10
  WriteText "Oh! そうなんですか?!<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ぶきの もちかえには<br>1ターンしょうひしますが<br>けっこう べんりなのでーす。<br>",$00
  PromptContinue
  SetPortrait $02,$10,$08
  WriteText "それぞれの ぶきに<br>ぞくせいのちがう わざを<br>セットしておくと<br>",$00
  PromptContinue
  WriteText "いかなるてきが あらわれても<br>ぶきを もちかえるだけで<br>らくに たたかえるのですわ。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "そのとおりでーす。<br>",$08,"さんも いちど<br>つかってみてくださーい。<br>",$00
  PromptContinue
  Unknown06 $D6,$09
  SetPortrait $06,$10,$08
  WriteText "それじゃあ ",$08,"<br>じゅんびは いいか?<br>",$00
  PromptContinue
  OptionSelect $02,$00,$84,$5B,$7C,$90,$6F,$59,$56,$79,$72,$52,$74,$10,$5B,$5D,$00,$00,$D1,$C4,$C2,$EC,$75,$67,$00,$01
  Unknown07 $1D,$0A,$02,$00,$01,$00,$20,$00
  Unknown07 $28,$0B,$02,$00,$01,$01,$20,$00
  Unknown0F $00,$01
  WriteText "すみません。<br>ぶきの もちかえについて<br>もういちど おねがいします。<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  WriteText "わかりました。<br>ぶきの もちかえについて<br>でーすね。<br>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "ぶきは せんとうちゅうに<br>もちかえることが<br>できるのでーす。<br>",$00
  PromptContinue
  WriteText "ぶきの もちかえには<br>1ターンつかって<br>しまいまーす。<br>",$00
  PromptContinue
  WriteText "でも かんがえて つかうと<br>とても ベンリで グッドな<br>ものなのでーす。<br>",$00
  PromptContinue
  WriteText "それぞれの ぶきに<br>ぞくせいのちがう わざを<br>セットしておけば<br>",$00
  PromptContinue
  WriteText "どんなてきが あらわれても<br>ぶきを もちかえるだけで<br>らくに たたかえるのでーす。<br>",$00
  PromptContinue
  Unknown06 $D6,$09
  Unknown0F $00,$01
  WriteText "はい バッチリです。<br>",$00
  PromptContinue
  SetPortrait $06,$11,$09
  WriteText "それじゃあ ",$08,"!<br>がんばっていこうぜ!!<br>",$00
  PromptContinue
  SetPortrait $02,$10,$08
  WriteText $08,"さん。<br>しなないていどに<br>がんばりなさい。<br>",$00
  PromptContinue
  SetPortrait $07,$11,$0A
  WriteText $08,"さん<br>レッツ ファイトでーす!!<br>",$00
  PromptContinue
  End
  End
CutsceneScript55_0End::


