; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 48 0", ROMX[$730E], BANK[$4B]
CutsceneScript48_0::
  SetPortrait $09,$00,$00
  Unknown0E $08
  Unknown12 $04
  Unknown02
  WriteText "オレは おおがみいちろう。<br>ていこくかげきだん<br>はなぐみの たいちょうだ。<br>",$00
  PromptContinue
  WriteText "ぶきは にとうりゅうの<br>カタナで せっきんせんなら<br>まかせてくれ。<br>",$00
  PromptContinue
  WriteText "きみは じっせんの<br>けいけんが すくないから<br>はじめは サポートするよ。<br>",$00
  PromptContinue
  WriteText "しばらくは オレが<br>かばってあげるから まずは<br>せんとうになれるんだ。<br>",$00
  PromptContinue
  WriteText "そして ともに<br>ていとの へいわのために<br>たたかおう!<br>",$00
  PromptContinue
  End
  End
CutsceneScript48_0End::


