; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 11 0", ROMX[$403F], BANK[$41]
CutsceneScript11_0::
  Unknown12 $05
  Unknown0F $00,$01
  Unknown02
  Unknown07 $E3,$33,$02,$04,$01,$01,$20,$00
  Unknown09 $5A
  Unknown0F $00,$01
  Unknown0C $01
  WriteText $FC,$6E,$52,$12,$65,$95,$54,$FC,$0D,$01,$07,$61,$54,$84,$10,$E0,$AC,$B6,$79,$6D,$72,$FA,$01,$08,$0D,$00
  PromptContinue
  WriteText $83,$54,$FF,$FF,$0D,$92,$71,$76,$72,$52,$6D,$9F,$0D,$00
  PromptContinue
  WriteText $76,$72,$6A,$A1,$10,$96,$81,$6E,$63,$9A,$6D,$5F,$77,$0D,$52,$71,$6D,$52,$10,$78,$79,$5A,$0D,$50,$71,$6D,$A1,$6E,$9B,$54,$FF,$FF,$0D,$00
  PromptContinue
  Unknown0C $02
  Unknown0E $02
  SetPortrait $0B,$11,$01
  WriteText $96,$5D,$10,$5B,$74,$5D,$9A,$6D,$9D,$7B,$9F,$0D,$9D,$6D,$65,$7D,$0D,$83,$66,$56,$6E,$10,$59,$56,$75,$9F,$0D,$00
  PromptContinue
  WriteText $74,$52,$61,$5D,$59,$60,$5B,$6E,$A1,$7C,$0D,$83,$5D,$65,$9A,$52,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $75,$7D,$10,$63,$71,$6B,$5D,$6E,$5F,$77,$0D,$50,$78,$6D,$A0,$10,$61,$61,$86,$96,$A1,$6E,$0D,$98,$94,$54,$A0,$10,$69,$72,$8F,$52,$67,$99,$9D,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$12,$02
  WriteText $50,$78,$6D,$7C,$10,$79,$A1,$8E,$7D,$0D,$E0,$AC,$B6,$5B,$7B,$A1,$61,$54,$56,$A1,$A0,$0D,$65,$97,$87,$99,$61,$76,$75,$67,$9F,$0D,$00
  PromptContinue
  WriteText $67,$61,$65,$8C,$56,$59,$97,$10,$E0,$AC,$B6,$5B,$7B,$A1,$0D,$61,$54,$56,$A1,$75,$10,$58,$59,$65,$78,$61,$76,$5A,$0D,$58,$61,$71,$74,$52,$99,$7C,$75,$67,$9F,$0D,$00
  PromptContinue
  WriteText $6B,$61,$75,$10,$61,$A1,$59,$52,$7D,$10,$50,$78,$6D,$79,$0D,$6B,$7C,$10,$60,$A1,$52,$A1,$A0,$10,$65,$97,$87,$74,$0D,$90,$97,$58,$54,$76,$10,$58,$90,$52,$8C,$67,$9F,$0D,$00
  PromptContinue
  WriteText $52,$52,$9D,$7B,$10,$08,$5D,$A1,$9F,$0D,$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText $75,$7D,$10,$74,$52,$61,$5D,$59,$60,$5B,$6E,$A1,$0D,$7D,$78,$5E,$8D,$7C,$10,$6D,$52,$6F,$95,$54,$A0,$0D,$65,$95,$54,$59,$52,$67,$99,$9D,$9F,$0D,$00
  PromptContinue
  WriteText $58,$58,$5A,$8D,$5D,$A1,$9F,$0D,$00
  PromptContinue
  SetPortrait $09,$01,$01
  WriteText $7D,$52,$9F,$0D,$00
  PromptContinue
  LIPSTimed $05,$02,$58,$58,$5A,$8D,$63,$A1,$10,$58,$80,$63,$65,$84,$98,$75,$67,$00,$00,$7D,$66,$8F,$8C,$65,$74,$00,$01
  Unknown07 $5A,$02,$02,$01,$01,$00
