; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 10 0", ROMX[$4003], BANK[$41]
CutsceneScript10_0::
  Unknown12 $05
  Unknown02
  Unknown0C $01
  Unknown0E $1D
  SetPortrait $11,$01,$01
  WriteText "なまえを にゅうりょくして<br>ちょうだい。<br>",$00
  PromptContinue
  Unknown1D
  Unknown0E $1D
  SetPortrait $11,$01,$01
  WriteText $08,"ちゃん<br>がんばってね。<br>",$00
  PromptContinue
  End
  End
CutsceneScript10_0End::


