; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 4E 0", ROMX[$7705], BANK[$4B]
CutsceneScript4E_0::
  SetPortrait $10,$00,$00
  Unknown0E $1A
  Unknown12 $04
  Unknown02
  WriteText "わたしたちは<br>",$01,$07,"アイ",$01,$08,"と",$01,$07,"ビ",$01,$08,"のせんし<br>バラぐみよ。<br>",$00
  PromptContinue
  SetPortrait $10,$01,$01
  WriteText "わたしは<br>ばらぐみの たいちょう<br>せいりゅういん ことね。<br>",$00
  PromptContinue
  SetPortrait $11,$01,$01
  WriteText "アタシは<br>おおた よきひこよぉ<br>チューして あげるわ",$0A,$02,$01,"7",$0A,$03,"<br>",$00
  PromptContinue
  SetPortrait $12,$00,$00
  WriteText "あの‥‥あたし‥‥<br>おか きくのじょう<br>って いいます。<br>",$00
  PromptContinue
  WriteText "だから‥‥<br>きくちゃんって<br>よんでください‥‥<br>",$00
  PromptContinue
  SetPortrait $10,$01,$01
  WriteText "フフフフ。<br>わたしたちは<br>ひみつぶたいなので‥‥<br>",$00
  PromptContinue
  SetPortrait $11,$01,$01
  WriteText "あうことは<br>あまり ないかも<br>しれないわねぇ",$0A,$02,$01,"7",$0A,$03,"<br>",$00
  PromptContinue
  SetPortrait $12,$00,$00
  WriteText "あの でも‥‥<br>よろしく おねがい<br>しますね‥‥<br>",$00
  PromptContinue
  SetPortrait $10,$01,$01
  WriteText "よろしく!<br>",$00
  PromptContinue
  End
  End
CutsceneScript4E_0End::


