; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 49 0", ROMX[$73D5], BANK[$4B]
CutsceneScript49_0::
  RSRESET
  SetPortrait $0B,$10,$00
  Unknown0E $0A
  Unknown12 $04
  Unknown02
  WriteText "よくきてくれたわね。<BR>わたしは ていこくかげきだん<BR>ふくしれい ふじえだかえで。<BR>",$00
  PromptContinue
  WriteText "あなたへの さくせんの<BR>しじは すべてわたしが<BR>おこないます。<BR>",$00
  PromptContinue
  SetPortrait $0B,$11,$01
  WriteText "はじめての にんむで<BR>たいへんだと おもうけど<BR>しっかりたのむわよ。<BR>",$00
  PromptContinue
  End
  End
CutsceneScript49_0End::


