; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 4D 0", ROMX[$7637], BANK[$4B]
CutsceneScript4D_0::
  SetPortrait $0F,$00,$00
  Unknown0E $0B
  Unknown12 $04
  Unknown02
  WriteText "やあ!<BR>オレは かやまゆういち。<BR>うみを あいするオトコだ。<BR>",$00
  PromptContinue
  WriteText "しゅみは ギターを<BR>ひくことだな。<BR>",$00
  PromptContinue
  Unknown13 $4D,$01
  WriteText "いいな～ ギターは。<BR>さわやかな ねいろで。<BR>",$00
  PromptContinue
  SetPortrait $0F,$04,$04
  WriteText "え? なにものだって?<BR>そんなこと どうでも<BR>いいじゃないか!<BR>",$00
  PromptContinue
  SetPortrait $0F,$00,$00
  WriteText "まぁ おおがみの<BR>かいぐんじだいの<BR>しんゆうと おぼえてくれ!<BR>",$00
  PromptContinue
  SetPortrait $0F,$01,$01
  WriteText "じゃあ これから<BR>よろしくたのむよ!<BR>アディオス!<BR>",$00
  PromptContinue
  End
  End
CutsceneScript4D_0End::


