; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 4E 0", ROMX[$7705], BANK[$4B]
CutsceneScript4E_0::
  SetPortrait $10,$00,$00
  Unknown0E $1A
  Unknown12 $04
  Unknown02
  WriteText "わたしたちは<BR>",CHARACTER_EXT_07,"アイ",CHARACTER_EXT_08,"と",CHARACTER_EXT_07,"ビ",CHARACTER_EXT_08,"のせんし<BR>バラぐみよ。<BR>",$00
  PromptContinue
  SetPortrait $10,$01,$01
  WriteText "わたしは<BR>ばらぐみの たいちょう<BR>せいりゅういん ことね。<BR>",$00
  PromptContinue
  SetPortrait $11,$01,$01
  WriteText "アタシは<BR>おおた よきひこよぉ<BR>チューして あげるわ",$0A,$02,CHARACTER_EXT_18,$0A,$03,"<BR>",$00
  PromptContinue
  SetPortrait $12,$00,$00
  WriteText "あの‥‥あたし‥‥<BR>おか きくのじょう<BR>って いいます。<BR>",$00
  PromptContinue
  WriteText "だから‥‥<BR>きくちゃんって<BR>よんでください‥‥<BR>",$00
  PromptContinue
  SetPortrait $10,$01,$01
  WriteText "フフフフ。<BR>わたしたちは<BR>ひみつぶたいなので‥‥<BR>",$00
  PromptContinue
  SetPortrait $11,$01,$01
  WriteText "あうことは<BR>あまり ないかも<BR>しれないわねぇ",$0A,$02,CHARACTER_EXT_18,$0A,$03,"<BR>",$00
  PromptContinue
  SetPortrait $12,$00,$00
  WriteText "あの でも‥‥<BR>よろしく おねがい<BR>しますね‥‥<BR>",$00
  PromptContinue
  SetPortrait $10,$01,$01
  WriteText "よろしく!<BR>",$00
  PromptContinue
  End
  End
CutsceneScript4E_0End::


