; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 46 0", ROMX[$719B], BANK[$4B]
CutsceneScript46_0::
  SetPortrait $07,$01,$01
  Unknown0E $1F
  Unknown12 $04
  Unknown02
  WriteText "チャオ!<BR>ソレッタ・おりひめでーす。<BR>",$00
  PromptContinue
  WriteText "ていとをまもるために<BR>わざわざ イタリアから<BR>やってきて やりました。<BR>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "わたしのワザは<BR>ゆびさきからでる<BR>れいりょくビームでーす!<BR>",$00
  PromptContinue
  WriteText "れいりょくビームは<BR>はなれた たくさんのてきも<BR>こうげきできるのでーす!<BR>",$00
  PromptContinue
  WriteText "どうです?<BR>スペシャル すばらしいと<BR>おもいませんかー?<BR>",$00
  PromptContinue
  WriteText "あなたも わたしを<BR>みならって まいにち<BR>しょうじんするのでーす。<BR>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText "いいですね?<BR>",$00
  PromptContinue
  End
  End
CutsceneScript46_0End::


