; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 46 0", ROMX[$719B], BANK[$4B]
CutsceneScript46_0::
  SetPortrait $07,$01,$01
  Unknown0E $1F
  Unknown12 $04
  Unknown02
  WriteText $C2,$E5,$AB,$FA,$0D,$BE,$EE,$C4,$C0,$F3,$58,$98,$80,$8F,$75,$FB,$67,$9F,$0D,$00
  PromptContinue
  WriteText $74,$52,$76,$A0,$8C,$90,$99,$6D,$8F,$79,$0D,$9D,$64,$9D,$64,$10,$A5,$C0,$EC,$A3,$59,$97,$0D,$92,$71,$74,$5B,$74,$10,$92,$98,$8C,$65,$6D,$9F,$0D,$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText $9D,$6D,$65,$7C,$F1,$B7,$7D,$0D,$94,$81,$63,$5B,$59,$97,$75,$99,$0D,$9A,$52,$98,$95,$5D,$D4,$FB,$E2,$75,$FB,$67,$FA,$0D,$00
  PromptContinue
  WriteText $9A,$52,$98,$95,$5D,$D4,$FB,$E2,$7D,$0D,$7D,$78,$9A,$6D,$10,$6D,$5D,$63,$A1,$7C,$74,$5B,$90,$0D,$61,$54,$60,$5B,$75,$5B,$99,$7C,$75,$FB,$67,$FA,$0D,$00
  PromptContinue
  WriteText $77,$54,$75,$67,$F9,$0D,$BA,$DB,$B8,$E5,$ED,$10,$67,$7E,$97,$65,$52,$76,$0D,$58,$90,$52,$8C,$69,$A1,$59,$FB,$F9,$0D,$00
  PromptContinue
  WriteText $50,$78,$6D,$90,$10,$9D,$6D,$65,$A0,$0D,$8D,$78,$97,$71,$74,$10,$8C,$52,$79,$6F,$0D,$65,$95,$54,$66,$A1,$67,$99,$7C,$75,$FB,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText $52,$52,$75,$67,$7B,$F9,$0D,$00
  PromptContinue
  End
  End
CutsceneScript46_0End::


