; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 5C 0", ROMX[$7577], BANK[$4D]
CutsceneScript5C_0::
  Unknown0E $1A
  Unknown0F $00,$01
  Unknown12 $05
  Unknown02
  Unknown07 $69,$03,$02,$04,$01,$01,$20,$00
  Unknown07 $C7,$01,$04,$87,$B6,$01,$FF,$20,$00
  WriteText $61,$54,$97,$A1,$63,$A1,$9F,$0D,$6F,$95,$71,$76,$52,$52,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  Unknown05 $87,$B3,$01,$00
  End
  SetPortrait $05,$20,$10
  WriteText $A1,$FF,$FF,$F9,$10,$78,$A1,$92,$0D,$08,$7D,$A1,$92,$78,$52,$59,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $61,$7C,$01,$07,$69,$71,$5F,$52,$68,$01,$08,$A0,$0D,$61,$54,$97,$A1,$63,$A1,$79,$10,$9D,$6D,$65,$74,$0D,$5D,$9A,$76,$10,$6D,$7C,$8C,$9A,$6D,$A1,$75,$67,$5A,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $69,$71,$5F,$52,$68,$F9,$0D,$77,$9A,$77,$9A,$FF,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $05,$23,$13
  WriteText $61,$FF,$FF,$61,$9A,$7D,$FA,$FA,$0D,$01,$07,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$01,$08,$7C,$0D,$69,$71,$5F,$52,$68,$92,$78,$52,$59,$FA,$FA,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $56,$71,$FA,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$71,$74,$0D,$58,$98,$80,$8F,$63,$A1,$92,$10,$EE,$CC,$63,$A1,$5A,$0D,$7C,$71,$74,$52,$99,$10,$5B,$6D,$52,$75,$67,$59,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $6B,$54,$92,$9F,$0D,$61,$54,$84,$76,$7D,$10,$80,$76,$50,$66,$6F,$5A,$71,$6D,$0D,$59,$71,$61,$96,$63,$5A,$50,$99,$10,$5B,$6D,$52,$92,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $96,$71,$65,$91,$FA,$0D,$90,$56,$74,$5B,$6D,$75,$FC,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $72,$5C,$7C,$10,$65,$93,$72,$60,$5B,$8C,$75,$79,$7D,$0D,$D1,$C4,$C2,$EC,$10,$72,$5D,$71,$76,$5D,$59,$97,$78,$9F,$0D,$00
  PromptContinue
  WriteText $08,$7D,$A1,$7D,$0D,$61,$54,$84,$75,$90,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$0D,$75,$90,$10,$67,$5B,$78,$7C,$A0,$72,$59,$71,$74,$78,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $61,$54,$84,$90,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$90,$0D,$67,$62,$52,$5B,$6D,$52,$92,$59,$97,$10,$5B,$84,$A1,$75,$0D,$7C,$98,$59,$56,$6D,$97,$A9,$A9,$75,$9F,$0D,$00
  PromptContinue
  Unknown05 $84,$85,$01,$01
  End
  WriteText $89,$78,$10,$5A,$A1,$7E,$71,$74,$78,$9F,$0D,$00
  PromptContinue
  Unknown0D $00,$00
  Unknown0F $00,$01
  Unknown09 $64
  End
  WriteText $61,$54,$97,$A1,$63,$A1,$9F,$0D,$6F,$95,$71,$76,$52,$52,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  Unknown05 $87,$B3,$01,$00
  End
  SetPortrait $05,$20,$10
  WriteText $A1,$FF,$FF,$F9,$10,$78,$A1,$92,$0D,$08,$7D,$A1,$92,$78,$52,$59,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $63,$71,$5B,$7C,$10,$69,$71,$5F,$52,$68,$0D,$52,$71,$6D,$52,$10,$78,$79,$7C,$69,$71,$5F,$52,$68,$0D,$6E,$71,$6D,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $D6,$D6,$D6,$FF,$FF,$10,$08,$7D,$A1,$9F,$0D,$5B,$52,$74,$10,$58,$77,$9B,$52,$6D,$97,$0D,$A3,$AC,$F5,$75,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$27,$17
  WriteText $61,$7C,$69,$71,$5F,$52,$68,$7D,$0D,$01,$07,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$01,$08,$7C,$0D,$69,$71,$5F,$52,$68,$78,$A1,$92,$FA,$FA,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $56,$71,$FA,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$71,$74,$0D,$58,$98,$80,$8F,$63,$A1,$92,$10,$EE,$CC,$63,$A1,$5A,$0D,$7C,$71,$74,$52,$99,$10,$5B,$6D,$52,$75,$67,$59,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $6B,$54,$92,$9F,$0D,$61,$54,$84,$76,$7D,$10,$80,$76,$50,$66,$6F,$5A,$71,$6D,$0D,$59,$71,$61,$96,$63,$5A,$50,$99,$10,$5B,$6D,$52,$92,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $61,$9A,$75,$10,$08,$7D,$A1,$90,$0D,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$79,$0D,$7C,$9A,$99,$96,$54,$79,$78,$99,$A1,$92,$FA,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $72,$5C,$7C,$10,$65,$93,$72,$60,$5B,$8C,$75,$79,$7D,$0D,$D1,$C4,$C2,$EC,$10,$72,$5D,$71,$76,$5D,$59,$97,$0D,$6D,$7C,$65,$8D,$79,$10,$8C,$71,$76,$5B,$9F,$0D,$00
  PromptContinue
  WriteText $61,$54,$84,$90,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$90,$0D,$67,$62,$52,$5B,$6D,$52,$92,$59,$97,$10,$5B,$84,$A1,$75,$0D,$7C,$98,$59,$56,$6D,$97,$A9,$A9,$75,$9F,$0D,$00
  PromptContinue
  Unknown05 $84,$85,$01,$01
  End
  WriteText $89,$78,$10,$5A,$A1,$7E,$71,$74,$78,$9F,$0D,$00
  PromptContinue
  Unknown0D $00,$00
  Unknown0F $00,$01
  Unknown09 $64
  End
  Unknown07 $20,$05,$04,$87,$B6,$01,$FF,$20,$00
  WriteText $61,$54,$97,$A1,$63,$A1,$9F,$0D,$6F,$95,$71,$76,$52,$52,$75,$65,$95,$54,$59,$F9,$0D,$00
  PromptContinue
  Unknown05 $87,$B3,$01,$00
  End
  SetPortrait $05,$20,$10
  WriteText $A1,$FF,$FF,$F9,$10,$78,$A1,$92,$0D,$08,$7D,$A1,$92,$78,$52,$59,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $61,$7C,$01,$07,$69,$71,$5F,$52,$68,$01,$08,$A0,$0D,$61,$54,$97,$A1,$63,$A1,$79,$10,$9D,$6D,$65,$74,$0D,$5D,$9A,$76,$10,$6D,$7C,$8C,$9A,$6D,$A1,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $69,$71,$5F,$52,$68,$F9,$0D,$77,$9A,$77,$9A,$FF,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $05,$23,$13
  WriteText $61,$FF,$FF,$61,$9A,$7D,$FA,$FA,$0D,$01,$07,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$01,$08,$7C,$0D,$69,$71,$5F,$52,$68,$92,$78,$52,$59,$FA,$FA,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $56,$71,$FA,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$71,$74,$0D,$58,$98,$80,$8F,$63,$A1,$92,$10,$EE,$CC,$63,$A1,$5A,$0D,$7C,$71,$74,$52,$99,$10,$5B,$6D,$52,$75,$67,$59,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $6B,$54,$92,$9F,$0D,$61,$54,$84,$76,$7D,$10,$80,$76,$50,$66,$6F,$5A,$71,$6D,$0D,$59,$71,$61,$96,$63,$5A,$50,$99,$10,$5B,$6D,$52,$92,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $96,$71,$65,$91,$FA,$0D,$90,$56,$74,$5B,$6D,$75,$FC,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $72,$5C,$7C,$10,$65,$93,$72,$60,$5B,$8C,$75,$79,$7D,$0D,$D1,$C4,$C2,$EC,$10,$72,$5D,$71,$76,$5D,$59,$97,$78,$9F,$0D,$00
  PromptContinue
  WriteText $08,$7D,$A1,$7D,$0D,$61,$54,$84,$75,$90,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$0D,$75,$90,$10,$67,$5B,$78,$7C,$A0,$72,$59,$71,$74,$78,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $61,$54,$84,$90,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$90,$0D,$67,$62,$52,$5B,$6D,$52,$92,$59,$97,$10,$5B,$84,$A1,$75,$0D,$7C,$98,$59,$56,$6D,$97,$A9,$A9,$75,$9F,$0D,$00
  PromptContinue
  Unknown05 $84,$85,$01,$01
  End
  WriteText $89,$78,$10,$5A,$A1,$7E,$71,$74,$78,$9F,$0D,$00
  PromptContinue
  Unknown0D $00,$00
  Unknown0F $00,$01
  Unknown09 $64
  End
  WriteText $61,$54,$97,$A1,$63,$A1,$9F,$0D,$6F,$95,$71,$76,$52,$52,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  Unknown05 $87,$B3,$01,$00
  End
  SetPortrait $05,$20,$10
  WriteText $A1,$FF,$FF,$F9,$10,$78,$A1,$92,$0D,$08,$7D,$A1,$92,$78,$52,$59,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $63,$71,$5B,$7C,$10,$69,$71,$5F,$52,$68,$0D,$52,$71,$6D,$52,$10,$78,$79,$7C,$69,$71,$5F,$52,$68,$0D,$6E,$71,$6D,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $D6,$D6,$D6,$FF,$FF,$10,$08,$7D,$A1,$9F,$0D,$5B,$52,$74,$10,$58,$77,$9B,$52,$6D,$97,$0D,$A3,$AC,$F5,$75,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$27,$17
  WriteText $61,$7C,$69,$71,$5F,$52,$68,$7D,$0D,$01,$07,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$01,$08,$7C,$0D,$69,$71,$5F,$52,$68,$78,$A1,$92,$FA,$FA,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $56,$71,$FA,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$71,$74,$0D,$58,$98,$80,$8F,$63,$A1,$92,$10,$EE,$CC,$63,$A1,$5A,$0D,$7C,$71,$74,$52,$99,$10,$5B,$6D,$52,$75,$67,$59,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $6B,$54,$92,$9F,$0D,$61,$54,$84,$76,$7D,$10,$80,$76,$50,$66,$6F,$5A,$71,$6D,$0D,$59,$71,$61,$96,$63,$5A,$50,$99,$10,$5B,$6D,$52,$92,$9F,$0D,$00
  PromptContinue
  SetPortrait $05,$25,$15
  WriteText $61,$9A,$75,$10,$08,$7D,$A1,$90,$0D,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$79,$0D,$7C,$9A,$99,$96,$54,$79,$78,$99,$A1,$92,$FA,$FA,$0D,$00
  PromptContinue
  SetPortrait $05,$20,$10
  WriteText $72,$5C,$7C,$10,$65,$93,$72,$60,$5B,$8C,$75,$79,$7D,$0D,$D1,$C4,$C2,$EC,$10,$72,$5D,$71,$76,$5D,$59,$97,$0D,$6D,$7C,$65,$8D,$79,$10,$8C,$71,$76,$5B,$9F,$0D,$00
  PromptContinue
  WriteText $61,$54,$84,$90,$10,$A3,$A5,$BD,$F5,$B0,$EB,$A5,$C9,$90,$0D,$67,$62,$52,$5B,$6D,$52,$92,$59,$97,$10,$5B,$84,$A1,$75,$0D,$7C,$98,$59,$56,$6D,$97,$A9,$A9,$75,$9F,$0D,$00
  PromptContinue
  Unknown05 $84,$85,$01,$01
  End
  WriteText $89,$78,$10,$5A,$A1,$7E,$71,$74,$78,$9F,$0D,$00
  PromptContinue
  Unknown0D $00,$00
  Unknown0F $00,$01
  Unknown09 $64
  End
  End
CutsceneScript5C_0End::


