; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 34 0", ROMX[$7E7E], BANK[$45]
CutsceneScript34_0::
  Unknown0E $16
  Unknown0F $00,$01
  Unknown12 $17
  Unknown02
  Unknown07 $7E,$09,$02,$04,$01,$01,$20,$00
  WriteText "さっき ミカサのなかで<br>ひろった ことわざじてん。<br>",$00
  PromptContinue
  Unknown05 $84,$9E,$01,$00
  End
  WriteText "たぶん おりひめさんのもの<br>だとおもうから<br>わたしにいこう。<br>",$00
  PromptContinue
  Unknown1E $1F
  WriteText "おりひめさん。<br>しつれいします。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText $08,"さん<br>どうしたですか?<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "こんなものを<br>ひろったのですが‥‥<br>おりひめさんのですか?<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "ことわざじてん?<br>Oh! それは わたしの<br>だいじなものでーす。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  Unknown1A $40,$97,$03,$97,$01,$06,$28,$00
  WriteText "わざわざ どーもです。<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "おりひめさん ことわざ<br>すきなんですか?<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "ことわざは サイコーでーす。<br>",$00
  PromptContinue
  WriteText "ショートワードのなかに<br>きょうくんや ふうしが<br>テンコもりでーす。<br>",$00
  PromptContinue
  WriteText "わたし たくさん たくさん<br>べんきょうしてまーす。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  db $01,$52,$8C,$59,$97,$10,$6B,$7C,$69,$52,$59,$7C,$0D,$52,$6F,$84,$A0,$10,$7D,$71,$82,$95,$54,$0D,$65,$8C,$FB,$67,$9F,$52 ; WriteText
CutsceneScript34_0End::


SECTION "Cutscene Script 34 1", ROMX[$4000], BANK[$46]
CutsceneScript34_1::
  db $52,$75,$67,$7B,$F9,$0D,$00 ; WriteText
  PromptContinue
  OptionSelectTimed $05,$03,$6E,$8C,$71,$74,$5B,$5D,$00,$00,$72,$71,$61,$8D,$A0,$52,$9A,$99,$00,$01,$8C,$6F,$5A,$52,$A0,$65,$74,$5B,$67,$99,$00,$02
  Unknown07 $C9,$01,$02,$01,$01,$00,$20,$00
  Unknown07 $8D,$03,$02,$01,$01,$01,$20,$00
  Unknown07 $02,$06,$02,$01,$01,$02,$20,$00
  Unknown06 $1B,$08
  Unknown0F $00,$01
  WriteText "はい どうぞ。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "わたる せけんに<br>おにいさん。<br>",$00
  PromptContinue
  WriteText "いっけん こわくみえる<br>おにいさんも ほんとうは<br>やさしいこころを もってる。<br>",$00
  PromptContinue
  WriteText "すなわち ほんとうに<br>つめたいひとは いない<br>ということを いってまーす。<br>",$00
  PromptContinue
  WriteText "つぎは‥‥<br>おにに かなぶん。<br>",$00
  PromptContinue
  WriteText "おにが かなぶんをもったら<br>つよいでーす。<br>てきなし ということでーす。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText "どーですか?<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "すごいですね おりひめさん。<br>にほんのことわざを しっかり<br>べんきょうしてるなんて。<br>",$00
  PromptContinue
  Unknown0D $07,$05
  WriteText "でも すこし まちがって<br>いましたよ。<br>",$00
  PromptContinue
  Unknown0D $07,$07
  WriteText "まず さいしょのは<br>わたる せけんに おにはなし<br>ですね。<br>",$00
  PromptContinue
  WriteText "つぎのは<br>おにに かなぼう<br>ですよ。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  Unknown1A $40,$97,$03,$97,$01,$06,$28,$00
  WriteText "Oh! ",$08,"さん<br>おしえてくれて<br>サンキューでーす。<br>",$00
  PromptContinue
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくれて<br>サンキューでした。チャオ",$0A,$02,$01,"7",$0A,$03,"<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "はい どうぞ。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "わたる せけんに<br>おにいさん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "はいはい。<br>せけんに おにいさんは<br>たくさんいますね。<br>",$00
  PromptContinue
  WriteText "おりひめさんも<br>カッコいい おにいさん<br>すきなんでしょ～?<br>",$00
  PromptContinue
  SetPortrait $07,$08,$08
  WriteText "いっけん こわくみえる<br>おにいさんも ほんとうは<br>やさしいこころを もってる。<br>",$00
  PromptContinue
  WriteText "すなわち ほんとうに<br>つめたいひとは いない<br>ということを いってまーす。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "つぎは‥‥<br>おにに かなぶん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "おにに かなぶん!?<br>かわいそうに かなぶんちゃん<br>にぎり つぶされています。<br>",$00
  PromptContinue
  SetPortrait $07,$08,$08
  WriteText "おにが かなぶんをもったら<br>つよいでーす。<br>てきなし ということでーす。<br>",$00
  PromptContinue
  SetPortrait $07,$03,$03
  WriteText "‥‥もー ",$08,"さん<br>ヘンな あいのて<br>いれないでくださーい。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "いやーすみません。<br>でも おりひめさん<br>すごいじゃないですか。<br>",$00
  PromptContinue
  Unknown0D $07,$05
  WriteText "すこし まちがってたとはいえ<br>にほんのことわざを しっかり<br>べんきょうしてるなんて。<br>",$00
  PromptContinue
  SetPortrait $07,$07,$07
  WriteText "どこ まちがってましたか?<br>",$00
  PromptContinue
  Unknown0F $00,$01
  Unknown0D $07,$00
  WriteText "まず さいしょのは<br>わたる せけんに おにはなし<br>ですね。<br>",$00
  PromptContinue
  WriteText "つぎのは<br>おにに かなぼう<br>ですよ。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  Unknown1A $40,$97,$03,$97,$01,$04,$28,$00
  WriteText "オッケー! わかりまーした。<br>おしえてくれて<br>サンキューでーす。<br>",$00
  PromptContinue
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくれて<br>サンキューでした。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "はい どうぞ。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "わたる せけんに<br>おにいさん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "ちがいますよ。ただしくは<br>わたる せけんに おにはなし<br>ですよ。<br>",$00
  PromptContinue
  SetPortrait $07,$08,$08
  WriteText "あっ! そうでした。<br>すみませーん。<br>え～と いみは‥‥<br>",$00
  PromptContinue
  WriteText "せけんには こわく おもえる<br>ひともいるが ほんとうはみな<br>やさしいこころを もってる。<br>",$00
  PromptContinue
  WriteText "すなわち ほんとうに<br>つめたいひとは いない<br>ということを いってまーす。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "つぎは‥‥<br>おにに かなぶん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "ちがいますよ。ただしくは<br>おにに かなぼう<br>ですよ。<br>",$00
  PromptContinue
  SetPortrait $07,$08,$08
  WriteText "あっ! そうでした。<br>すみませーん。<br>え～と いみは‥‥<br>",$00
  PromptContinue
  WriteText "おにが かなぼうをもったら<br>つよいでーす。<br>てきなし ということでーす。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "おりひめさん もうすこし<br>しっかりと べんきょう<br>してください。<br>",$00
  PromptContinue
  SetPortrait $07,$03,$03
  WriteText "そんなに きつい いいかた<br>しなくても いーと<br>おもいまーす!<br>",$00
  PromptContinue
  WriteText "わたし がいこくじんでーす。<br>でも いっしょうけんめい<br>べんきょうしていまーす。<br>",$00
  PromptContinue
  WriteText "そんな つめたいめでみないで<br>ひろいこころで<br>みてくださーい。<br>",$00
  PromptContinue
  SetPortrait $07,$06,$06
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "はい どうぞ。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "わたる せけんに<br>おにいさん。<br>",$00
  PromptContinue
  WriteText "いっけん こわくみえる<br>おにいさんも ほんとうは<br>やさしいこころを もってる。<br>",$00
  PromptContinue
  WriteText "すなわち ほんとうに<br>つめたいひとは いない<br>ということを いってまーす。<br>",$00
  PromptContinue
  WriteText "つぎは‥‥<br>おにに かなぶん。<br>",$00
  PromptContinue
  WriteText "おにが かなぶんをもったら<br>つよいでーす。<br>てきなし ということでーす。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText "どーですか?<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "なんか チョットちがうような<br>きもしましたが すごいですね<br>おりひめさん。<br>",$00
  PromptContinue
  Unknown0D $07,$05
  Unknown0F $00,$01
  WriteText "にほんのことわざを しっかり<br>べんきょう しているなんて。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくれて<br>サンキューでした。<br>",$00
  PromptContinue
  End
  WriteText "さっき ミカサのなかで<br>ひろった ことわざじてん。<br>",$00
  PromptContinue
  Unknown05 $84,$9E,$01,$00
  End
  WriteText "きっと おりひめさんのもの<br>でしょうから<br>わたしにいきましょう。<br>",$00
  PromptContinue
  Unknown1E $1F
  WriteText "おりひめさん。<br>しつれいします。<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "あら ",$08,"さん<br>どうしたですか?<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "こんなものを<br>ひろったのですが‥‥<br>おりひめさんのですか?<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "ことわざじてん?<br>Oh! それは わたしの<br>だいじなものでーす。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  Unknown1A $40,$97,$03,$97,$01,$06,$28,$00
  WriteText "わざわざ どーもです。<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "おりひめさん ことわざ<br>すきなんですか?<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "ことわざは サイコーでーす。<br>",$00
  PromptContinue
  WriteText "ショートワードのなかに<br>きょうくんや ふうしが<br>テンコもりでーす。<br>",$00
  PromptContinue
  WriteText "わたし たくさん たくさん<br>べんきょうしてまーす。<br>",$00
  PromptContinue
  WriteText "わたる せけんに<br>おにはなし。<br>",$00
  PromptContinue
  WriteText "せけんには こわく おもえる<br>ひともいるが ほんとうはみな<br>やさしいこころを もってる。<br>",$00
  PromptContinue
  WriteText "すなわち ほんとうに<br>つめたいひとは いない<br>ということを いってまーす。<br>",$00
  PromptContinue
  WriteText "そして‥‥<br>おにに かなぼう。<br>",$00
  PromptContinue
  WriteText "おにが かなぼうをもったら<br>つよいでーす。<br>てきなし ということでーす。<br>",$00
  PromptContinue
  WriteText "そして‥‥<br>ネコにこうばん。<br>",$00
  PromptContinue
  WriteText "ネコをこうばんに<br>つれていっても いみがない<br>ということでーす。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText "どーですか?<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "スゴイ スゴイ!<br>おりひめさん!!<br>",$00
  PromptContinue
  Unknown0D $07,$05
  WriteText "にほんのことわざを しっかり<br>べんきょうしてるなんて<br>えらいですよ。<br>",$00
  PromptContinue
  WriteText "でも さいごのは まちがって<br>いましたよ。<br>",$00
  PromptContinue
  Unknown0D $07,$07
  WriteText "ただしくは<br>ネコに‥‥‥‥<br>",$00
  PromptContinue
  OptionSelectTimed $05,$03,$61,$7E,$A1,$00,$00,$61,$7E,$A1,$64,$8F,$00,$01,$62,$7D,$A1,$00,$02
  Unknown07 $62,$0C,$02,$01,$01,$00,$20,$00
  Unknown07 $2E,$0D,$02,$01,$01,$01,$20,$00
  Unknown07 $F6,$0D,$02,$01,$01,$02,$20,$00
  Unknown06 $BA,$0E
  Unknown0F $00,$01
  WriteText "ネコにこばん<br>ですよ。<br>",$00
  PromptContinue
  SetPortrait $07,$07,$07
  WriteText "Oh! そーでした。<br>ネコにこばん でーす。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText "ネコにこばんを あたえても<br>いみがない。<br>そーいうことでーすね。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  Unknown1A $40,$97,$03,$97,$01,$06,$28,$00
  WriteText $08,"さん<br>おしえてくれて<br>サンキューでーす。<br>",$00
  PromptContinue
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくれて<br>サンキューでした。チャオ",$0A,$02,$01,"7",$0A,$03,"<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "ネコにこばんざめ<br>ですよ。<br>",$00
  PromptContinue
  SetPortrait $07,$08,$08
  WriteText "こばんざめ?‥‥‥‥‥‥‥‥<br>‥‥‥‥‥‥‥‥‥‥‥‥‥‥<br>",$00
  PromptContinue
  SetPortrait $07,$06,$06
  WriteText "ちがいまーす!<br>こばん!!<br>ネコにこばん でーす!!!<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "ネコにこばんを あたえても<br>いみがない。<br>そーいうことでーす。<br>",$00
  PromptContinue
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくれて<br>サンキューでした。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "ネコにごはん ですよ。<br>",$00
  PromptContinue
  SetPortrait $07,$08,$08
  WriteText "ごはん?<br>ネコにごはんを あげたら<br>たべるだけでーす!<br>",$00
  PromptContinue
  SetPortrait $07,$06,$06
  WriteText "ちがいまーす!<br>こばん!!<br>ネコにこばん でーす!!!<br>",$00
  PromptContinue
  SetPortrait $07,$00,$00
  WriteText "ネコにこばんを あたえても<br>いみがない。<br>そーいうことでーす。<br>",$00
  PromptContinue
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくれて<br>サンキューでした。<br>",$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText "‥‥‥‥‥‥‥‥‥‥‥‥‥‥<br>",$00
  PromptContinue
  SetPortrait $07,$07,$07
  WriteText "あっ! おもいだしまーした。<br>",$00
  PromptContinue
  SetPortrait $07,$01,$01
  WriteText "ネコにこばん でーす。<br>",$00
  PromptContinue
  WriteText "ネコにこばんを あたえても<br>いみがない。<br>そーいうことでーす。<br>",$00
  PromptContinue
  WriteText "わたし このじてんで<br>もっと もっと<br>べんきょうしまーす。<br>",$00
  PromptContinue
  WriteText "それじゃ ",$08,"さん<br>わざわざ とどけてくれて<br>サンキューでした。<br>",$00
  PromptContinue
  End
  End
CutsceneScript34_1End::


