; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 12 0", ROMX[$6986], BANK[$42]
CutsceneScript12_0::
  Unknown0E $16
  Unknown12 $09
  Unknown02
  Unknown07 $82,$02,$02,$04,$01,$01,$20,$00
  Unknown07 $81,$00,$02,$05,$01,$01,$20,$00
  Unknown07 $E9,$00,$02,$05,$01,$02,$20,$00
  Unknown07 $D2,$00,$02,$05,$01,$03,$20,$00
  Unknown07 $98,$00,$02,$05,$01,$04,$20,$00
  Unknown07 $12,$01,$02,$05,$01,$05,$20,$00
  Unknown07 $56,$00,$02,$05,$01,$06,$20,$00
  Unknown07 $BB,$00,$02,$05,$01,$07,$20,$00
  Unknown07 $32,$01,$02,$05,$01,$08,$20,$00
  SetPortrait $06,$11,$09
  WriteText "よう ",$08,"!<br>ぶじ もどってきたな?<br>げんきそうで なによりだぜ。<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $01,$11,$09
  WriteText $08,"さん<br>おかえりなさい。<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $04,$11,$09
  WriteText $08,"おかえり!!<br>ねぇ ねぇ<br>おもしろかったー?!<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $07,$11,$0A
  WriteText $08,"さん<br>おかえりでーす。<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $03,$10,$08
  WriteText $08,"くん。<br>おつかれさま。<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $02,$10,$08
  WriteText "あら どうやら ぶじに<br>もどってきた ようですわね<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $05,$10,$08
  WriteText $08,"はん おかえり。<br>おつかれさんやったな。<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $08,$10,$08
  WriteText "‥‥‥‥にんむ<br>ごくろう。<br>",$00
  PromptContinue
  Unknown06 $4A,$01
  SetPortrait $0C,$11,$01
  WriteText "おかえりなさい<br>",$08,"さん。<br>",$00
  PromptContinue
  WriteText "つばきを たすけてくれて<br>ありがとうございました。<br>",$00
  PromptContinue
  SetPortrait $0D,$11,$01
  WriteText "おかえり! ",$08,"くん。<br>つばきのこと ありがとうね。<br>",$00
  PromptContinue
  SetPortrait $0B,$11,$01
  WriteText "おかえりなさい。おおがみくん<br>",$08,"くん。<br>ごくろうだったわね。<br>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "さっそくだけど<br>ほうこくを おねがいするわ。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "はい ほうこくします。<br>",$00
  PromptContinue
  WriteText "ミカサに まものがいました。<br>また なぜか まちのひとも<br>ミカサのなかに いました。<br>",$00
  PromptContinue
  WriteText "やはり ミカサでは<br>なにか おこっていると<br>かんがえられます。<br>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "わかったわ。<br>ぶんせきを いそぎましょう。<br>",$00
  PromptContinue
  WriteText $08,"くんは<br>つぎの しじがあるまで<br>やすんでいてちょうだい。<br>",$00
  PromptContinue
  End
  Unknown07 $F6,$02,$02,$05,$01,$01,$20,$00
  Unknown07 $87,$03,$02,$05,$01,$02,$20,$00
  Unknown07 $60,$03,$02,$05,$01,$03,$20,$00
  Unknown07 $26,$03,$02,$05,$01,$04,$20,$00
  Unknown07 $CC,$03,$02,$05,$01,$05,$20,$00
  Unknown07 $CA,$02,$02,$05,$01,$06,$20,$00
  Unknown07 $49,$03,$02,$05,$01,$07,$20,$00
  Unknown07 $EC,$03,$02,$05,$01,$08,$20,$00
  SetPortrait $06,$11,$09
  WriteText $08,"! おかえり!<br>ぶじにかえってきたな～。<br>がんばったじゃないか。<br>",$00
  PromptContinue
  Unknown06 $04,$04
  SetPortrait $01,$11,$09
  WriteText $08,"さん<br>おかえりなさい。<br>",$00
  PromptContinue
  SetPortrait $01,$11,$09
  WriteText "おおがみさんも<br>おつかれさまです。<br>",$00
  PromptContinue
  Unknown06 $04,$04
  SetPortrait $04,$11,$09
  WriteText $08,"おかえり!!<br>ねぇ ねぇ<br>おもしろかったー?!<br>",$00
  PromptContinue
  Unknown06 $04,$04
  SetPortrait $07,$11,$0A
  WriteText $08,"さん<br>おかえりでーす。<br>",$00
  PromptContinue
  Unknown06 $04,$04
  SetPortrait $03,$10,$08
  WriteText $08," なんとかぶじに<br>もどってきたようね。<br>おつかれさま。<br>",$00
  PromptContinue
  Unknown06 $04,$04
  SetPortrait $02,$10,$08
  WriteText "あら どうやら ぶじに<br>もどってきた ようですわね<br>",$08,"さん。<br>",$00
  PromptContinue
  Unknown06 $04,$04
  WriteText "しょういに ごめいわくを<br>かけてないでしょうね。<br>",$00
  PromptContinue
  SetPortrait $05,$10,$08
  WriteText $08,"はん おかえり。<br>おつかれさんやったな。<br>",$00
  PromptContinue
  Unknown06 $04,$04
  SetPortrait $08,$10,$08
  WriteText "‥‥‥‥にんむ<br>ごくろう。<br>",$00
  PromptContinue
  Unknown06 $04,$04
  SetPortrait $0C,$11,$01
  WriteText "おかえりなさい<br>",$08,"さん。<br>",$00
  PromptContinue
  WriteText "つばきを たすけてくれて<br>ありがとうございました。<br>",$00
  PromptContinue
  SetPortrait $0D,$11,$01
  WriteText "おかえり! ",$08,"さん。<br>つばきのこと ありがとうね。<br>",$00
  PromptContinue
  SetPortrait $0B,$11,$01
  WriteText "おかえりなさい。<br>おおがみくん ",$08,"。<br>ごくろうだったわね。<br>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "さっそくだけど<br>ほうこくを おねがいするわ。<br>",$00
  PromptContinue
  Unknown0F $00,$01
  WriteText "はい ほうこくします。<br>",$00
  PromptContinue
  WriteText "ミカサに まものがいました。<br>また なぜか まちのひとも<br>ミカサのなかに いました。<br>",$00
  PromptContinue
  WriteText "やはり ミカサでは<br>なにか おこっていると<br>かんがえられます。<br>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "わかったわ。<br>ぶんせきを いそぎましょう。<br>",$00
  PromptContinue
  WriteText $08,"は<br>つぎの しじがあるまで<br>やすんでいてちょうだい。<br>",$00
  PromptContinue
  End
  End
CutsceneScript12_0End::


