; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 1A 0", ROMX[$656F], BANK[$43]
CutsceneScript1A_0::
  RSRESET
  Unknown0F $00,$01
  Unknown12 $05
  Unknown02
  Unknown09 $5A
  Unknown0C $01
  WriteText "～だい4しょう～<BR> ",CHARACTER_EXT_07,"くらやみからのSOS",CHARACTER_EXT_08,"<BR>",$00
  PromptContinue
  Unknown0C $02
  Unknown0E $16
  SetPortrait $0B,$10,$00
  Unknown07 $EA,$02,$02,$04,$01,$01,$20,$00
  WriteText "みんな あつまってるわね。<BR>では はじめましょう。<BR>",$00
  PromptContinue
  WriteText "こんかい あらためて<BR>わかったことが あります。<BR>",$00
  PromptContinue
  SetPortrait $03,$12,$0A
  WriteText "あきらかに ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>ねらっている なぞのてきが<BR>ミカサにいる‥‥<BR>",$00
  PromptContinue
  WriteText "そうですね かえでさん。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "そうよ。<BR>",$00
  PromptContinue
  SetPortrait $08,$10,$08
  WriteText "でも だれが なんのために<BR>ということは <BR>まだ わかっていない‥‥<BR>",$00
  PromptContinue
  SetPortrait $01,$12,$0A
  WriteText CHARACTER_EXT_07,"けん",CHARACTER_EXT_08,"を まもっていた<BR>まものが さいごに いった<BR>ことば‥‥<BR>",$00
  PromptContinue
  SetPortrait $05,$12,$0A
  WriteText "「これで かったと<BR> おもうなよ」って<BR>どういう いみなんやろ?<BR>",$00
  PromptContinue
  SetPortrait $09,$10,$07
  WriteText "それはおそらく まものが<BR>ミカサのなかに まだまだ<BR>いるって ことじゃないか。<BR>",$00
  PromptContinue
  SetPortrait $04,$10,$08
  WriteText "ほかの",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"も<BR>まものに とられてるの?<BR>",$00
  PromptContinue
  SetPortrait $06,$12,$0A
  WriteText "その かのうせいは<BR>たかいな。<BR>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "てきは ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>つかって なにをやろうと<BR>しているのでーすか?<BR>",$00
  PromptContinue
  SetPortrait $02,$10,$08
  WriteText "それが わからないから<BR>しらべてるんじゃ<BR>ありませんこと。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "いまは てきのしょうたいも<BR>てきのもくてきも<BR>わからないわ。<BR>",$00
  PromptContinue
  SetPortrait $03,$12,$0A
  WriteText "だから ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"をはやく<BR>かいしゅうしないと<BR>なにがおこるか わからない‥<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "そう ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>いっこくも はやく<BR>かいしゅう しなきゃ‥‥<BR>",$00
  PromptContinue
  WriteText "こんかいは <NAME>くんの<BR>ほかに もうひとつの<BR>チームを だしましょう。<BR>",$00
  PromptContinue
  WriteText "2つのチームで <BR>いっきに かたを<BR>つけるのよ。<BR>",$00
  PromptContinue
  WriteText "カンナ アイリス。<BR>あなたたち ふたりに<BR>おねがいするわ。<BR>",$00
  PromptContinue
  SetPortrait $0B,$12,$02
  WriteText "では <NAME>くん<BR>しゅつどう!<BR>",$00
  PromptContinue
  End
  WriteText "みんな あつまってるわね。<BR>では はじめましょう。<BR>",$00
  PromptContinue
  WriteText "こんかい あらためて<BR>わかったことが あるわ。<BR>",$00
  PromptContinue
  SetPortrait $03,$12,$0A
  WriteText "あきらかに ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>ねらっている なぞのてきが<BR>ミカサにいる‥‥<BR>",$00
  PromptContinue
  WriteText "そうですね かえでさん。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "そうよ。<BR>",$00
  PromptContinue
  SetPortrait $08,$10,$08
  WriteText "でも だれが なんのために<BR>ということは <BR>まだ わかっていない‥‥<BR>",$00
  PromptContinue
  SetPortrait $01,$12,$0A
  WriteText CHARACTER_EXT_07,"けん",CHARACTER_EXT_08,"を まもっていた<BR>まものが さいごに いった<BR>ことば‥‥<BR>",$00
  PromptContinue
  SetPortrait $05,$12,$0A
  WriteText "「これで かったと<BR> おもうなよ」って<BR>どういう いみなんやろ?<BR>",$00
  PromptContinue
  SetPortrait $09,$10,$07
  WriteText "それはおそらく まものが<BR>ミカサのなかに まだまだ<BR>いるって ことじゃないか。<BR>",$00
  PromptContinue
  SetPortrait $04,$10,$08
  WriteText "ほかの",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"も<BR>まものに とられてるの?<BR>",$00
  PromptContinue
  SetPortrait $06,$12,$0A
  WriteText "その かのうせいは<BR>たかいな。<BR>",$00
  PromptContinue
  SetPortrait $07,$10,$09
  WriteText "てきは ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>つかって なにをやろうと<BR>しているのでーすか?<BR>",$00
  PromptContinue
  SetPortrait $02,$10,$08
  WriteText "それが わからないから<BR>しらべてるんじゃ<BR>ありませんこと。<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "いまは てきのしょうたいも<BR>てきのもくてきも<BR>わからないわ。<BR>",$00
  PromptContinue
  SetPortrait $03,$12,$0A
  WriteText "だから ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"をはやく<BR>かいしゅうしないと<BR>なにがおこるか わからない‥<BR>",$00
  PromptContinue
  SetPortrait $0B,$10,$00
  WriteText "そう ",CHARACTER_EXT_07,"まじんき",CHARACTER_EXT_08,"を<BR>いっこくも はやく<BR>かいしゅう しなきゃ‥‥<BR>",$00
  PromptContinue
  WriteText "こんかいは <NAME>の<BR>ほかに もうひとつの<BR>チームを だしましょう。<BR>",$00
  PromptContinue
  WriteText "2つのチームで <BR>いっきに かたを<BR>つけるのよ。<BR>",$00
  PromptContinue
  WriteText "カンナ アイリス。<BR>あなたたち ふたりに<BR>おねがいするわ。<BR>",$00
  PromptContinue
  SetPortrait $0B,$12,$02
  WriteText "では <NAME><BR>しゅつどう!<BR>",$00
  PromptContinue
  End
  End
CutsceneScript1A_0End::


