; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 41 0", ROMX[$6E96], BANK[$4B]
CutsceneScript41_0::
  SetPortrait $02,$00,$00
  Unknown0E $0D
  Unknown12 $04
  Unknown02
  WriteText $9D,$6D,$5D,$65,$7D,$0D,$7D,$78,$5E,$8D,$7C,$10,$C9,$C4,$D8,$BA,$C0,$A3,$0D,$59,$A1,$64,$5B,$10,$67,$8D,$9A,$75,$67,$9D,$9F,$0D,$00
  PromptContinue
  WriteText $9D,$6D,$5D,$65,$7C,$76,$5D,$5C,$7D,$0D,$59,$A1,$64,$5B,$83,$54,$66,$A1,$98,$93,$54,$7C,$0D,$78,$5C,$78,$6D,$66,$93,$72,$10,$75,$67,$7C,$9F,$0D,$00
  PromptContinue
  SetPortrait $02,$01,$01
  WriteText $52,$6F,$77,$79,$10,$6D,$5D,$63,$A1,$7C,$74,$5B,$A0,$0D,$94,$54,$5A,$79,$10,$78,$5C,$7D,$97,$54,$9F,$0D,$61,$9A,$5A,$10,$9D,$6D,$5D,$65,$7C,$81,$5A,$5D,$9F,$0D,$00
  PromptContinue
  SetPortrait $02,$00,$00
  WriteText $8C,$4F,$10,$50,$78,$6D,$90,$10,$9D,$6D,$5D,$65,$7C,$0D,$66,$91,$8C,$79,$78,$97,$78,$52,$96,$54,$0D,$65,$71,$59,$98,$10,$58,$92,$98,$78,$63,$52,$78,$9F,$0D,$00
  PromptContinue
  End
  End
CutsceneScript41_0End::


