; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

SECTION "Cutscene Script 37 0", ROMX[$5D45], BANK[$46]
CutsceneScript37_0::
  Unknown0E $16
  Unknown0F $00,$01
  Unknown12 $17
  Unknown02
  Unknown07 $A6,$02,$02,$04,$01,$01,$20,$00
  WriteText $63,$71,$5B,$8D,$72,$5F,$6D,$0D,$61,$7C,$10,$54,$6F,$93,$54,$7C,$89,$A1,$FF,$FF,$0D,$00
  PromptContinue
  Unknown05 $84,$B8,$01,$00
  End
  WriteText $EE,$CC,$63,$A1,$7C,$10,$76,$61,$9B,$86,$0D,$90,$71,$74,$52,$71,$74,$8D,$96,$54,$9F,$0D,$00
  PromptContinue
  Unknown1E $1C
  WriteText $EE,$CC,$63,$A1,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $08,$0D,$78,$79,$59,$96,$54,$F9,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $61,$A1,$78,$10,$89,$A1,$A0,$0D,$8D,$72,$5F,$6D,$7C,$75,$67,$5A,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $89,$A1,$FF,$FF,$F9,$0D,$54,$6F,$93,$54,$7C,$89,$A1,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $50,$50,$FF,$FF,$0D,$6B,$9A,$7D,$10,$DD,$B0,$7C,$6E,$96,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  Unknown1A $40,$98,$03,$98,$01,$06,$28,$00
  WriteText $9D,$64,$9D,$64,$10,$50,$98,$5A,$76,$54,$9F,$0D,$08,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $EE,$CC,$63,$A1,$71,$74,$10,$96,$5D,$0D,$96,$6C,$97,$A0,$10,$8D,$50,$60,$74,$8C,$67,$96,$7B,$9F,$0D,$6B,$65,$74,$10,$6B,$7C,$89,$A1,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $EE,$CC,$63,$A1,$7D,$10,$54,$6F,$93,$54,$5A,$0D,$67,$5B,$78,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $67,$5B,$76,$52,$54,$59,$0D,$5B,$95,$54,$8D,$7D,$50,$99,$96,$9F,$0D,$00
  PromptContinue
  WriteText $08,$10,$54,$6F,$93,$54,$79,$7D,$0D,$5B,$95,$54,$8D,$5A,$10,$78,$52,$F9,$0D,$00
  PromptContinue
  OptionSelectTimed $03,$02,$50,$99,$00,$00,$78,$52,$00,$01
  Unknown07 $55,$01,$02,$01,$01,$00,$20,$00
  Unknown07 $E2,$01,$02,$01,$01,$01,$20,$00
  Unknown06 $1E,$02
  Unknown0F $00,$01
  WriteText $50,$98,$8C,$67,$96,$9F,$0D,$8E,$60,$A1,$79,$10,$80,$9B,$5A,$99,$0D,$6E,$52,$54,$6F,$93,$54,$FF,$FF,$75,$67,$90,$A1,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  Unknown1A $40,$98,$03,$98,$01,$06,$28,$00
  WriteText $6B,$54,$6E,$7B,$9F,$0D,$54,$6F,$93,$54,$7C,$10,$80,$9B,$5A,$98,$7D,$0D,$7D,$74,$65,$78,$52,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $DD,$B0,$90,$10,$52,$72,$59,$10,$8E,$60,$A1,$7C,$0D,$54,$6F,$93,$54,$79,$10,$52,$5F,$6D,$97,$FF,$FF,$0D,$76,$10,$58,$90,$71,$74,$99,$A1,$6E,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  WriteText $6B,$9A,$66,$91,$50,$10,$08,$0D,$8C,$6D,$FF,$FF,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $6B,$54,$75,$67,$7B,$FF,$FF,$0D,$77,$6F,$97,$59,$76,$52,$56,$7E,$10,$78,$52,$0D,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $6B,$54,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $6B,$9A,$66,$91,$50,$10,$08,$0D,$8C,$6D,$FF,$FF,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$0D,$5B,$95,$54,$8D,$10,$50,$99,$10,$78,$52,$71,$74,$0D,$59,$A1,$5A,$56,$6D,$61,$76,$10,$78,$52,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $6B,$54,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $6D,$8C,$79,$7D,$10,$89,$65,$6C,$97,$A0,$0D,$8D,$74,$8D,$99,$7C,$90,$52,$52,$9F,$0D,$61,$61,$9B,$5A,$58,$6F,$72,$5D,$FF,$FF,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $6B,$54,$75,$67,$7B,$9F,$0D,$52,$52,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  WriteText $6B,$9A,$66,$91,$50,$10,$08,$0D,$8C,$6D,$FF,$FF,$0D,$00
  PromptContinue
  End
  WriteText $63,$71,$5B,$8D,$72,$5F,$6D,$0D,$61,$7C,$10,$54,$6F,$93,$54,$7C,$89,$A1,$FF,$FF,$0D,$00
  PromptContinue
  Unknown05 $84,$B8,$01,$00
  End
  WriteText $EE,$CC,$63,$A1,$7C,$10,$76,$61,$9B,$86,$0D,$90,$71,$74,$52,$71,$74,$8D,$96,$54,$9F,$0D,$00
  PromptContinue
  Unknown1E $1C
  WriteText $EE,$CC,$63,$A1,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $08,$0D,$78,$79,$59,$96,$54,$F9,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $61,$A1,$78,$10,$89,$A1,$A0,$0D,$8D,$72,$5F,$6D,$7C,$75,$67,$5A,$FF,$FF,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $89,$A1,$FF,$FF,$F9,$0D,$54,$6F,$93,$54,$7C,$89,$A1,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $50,$50,$FF,$FF,$0D,$6B,$9A,$7D,$10,$DD,$B0,$7C,$6E,$96,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  Unknown1A $40,$98,$03,$98,$01,$06,$28,$00
  WriteText $9D,$64,$9D,$64,$10,$50,$98,$5A,$76,$54,$9F,$0D,$08,$9F,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $EE,$CC,$63,$A1,$71,$74,$10,$96,$5D,$0D,$96,$6C,$97,$A0,$10,$8D,$50,$60,$74,$8C,$67,$96,$7B,$9F,$0D,$6B,$65,$74,$10,$6B,$7C,$89,$A1,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $EE,$CC,$63,$A1,$7D,$10,$54,$6F,$93,$54,$5A,$0D,$67,$5B,$78,$A1,$75,$67,$59,$F9,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $67,$5B,$76,$52,$54,$59,$0D,$5B,$95,$54,$8D,$7D,$50,$99,$96,$9F,$0D,$00
  PromptContinue
  WriteText $08,$10,$54,$6F,$93,$54,$79,$7D,$0D,$5B,$95,$54,$8D,$5A,$10,$78,$52,$F9,$0D,$00
  PromptContinue
  OptionSelectTimed $06,$02,$50,$99,$00,$00,$78,$52,$00,$01
  Unknown07 $EA,$03,$02,$01,$01,$00,$20,$00
  Unknown07 $7E,$04,$02,$01,$01,$01,$20,$00
  Unknown06 $BA,$04
  Unknown0F $00,$01
  WriteText $50,$98,$8C,$67,$96,$9F,$0D,$89,$65,$7D,$10,$5B,$9A,$52,$75,$67,$65,$0D,$94,$8F,$5A,$10,$50,$98,$8C,$67,$59,$97,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  Unknown1A $40,$98,$03,$98,$01,$06,$28,$00
  WriteText $6B,$54,$6E,$7B,$9F,$0D,$7D,$74,$65,$78,$5D,$10,$80,$9B,$5A,$71,$74,$52,$99,$0D,$54,$6F,$93,$54,$79,$7D,$10,$94,$8F,$5A,$50,$99,$9F,$0D,$00
  PromptContinue
  WriteText $DD,$B0,$90,$10,$52,$72,$59,$10,$61,$54,$6E,$52,$78,$0D,$54,$6F,$93,$54,$79,$10,$52,$5F,$6D,$97,$FF,$FF,$0D,$76,$10,$58,$90,$71,$74,$99,$A1,$6E,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  WriteText $6B,$9A,$66,$91,$50,$10,$08,$0D,$8C,$6D,$FF,$FF,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $6B,$54,$75,$67,$7B,$FF,$FF,$0D,$77,$6F,$97,$59,$76,$52,$56,$7E,$10,$78,$52,$0D,$75,$67,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $6B,$54,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $6B,$9A,$66,$91,$50,$10,$08,$0D,$8C,$6D,$FF,$FF,$0D,$00
  PromptContinue
  End
  Unknown0F $00,$01
  WriteText $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$0D,$5B,$95,$54,$8D,$10,$50,$99,$10,$78,$52,$71,$74,$0D,$59,$A1,$5A,$56,$6D,$61,$76,$10,$78,$52,$75,$67,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$00,$00
  WriteText $6B,$54,$FF,$FF,$0D,$00
  PromptContinue
  WriteText $6D,$8C,$79,$7D,$10,$89,$65,$6C,$97,$A0,$0D,$8D,$74,$8D,$99,$7C,$90,$52,$52,$9F,$0D,$61,$61,$9B,$5A,$58,$6F,$72,$5D,$FF,$FF,$0D,$00
  PromptContinue
  Unknown0F $00,$01
  WriteText $6B,$54,$75,$67,$7B,$9F,$0D,$5B,$9A,$52,$75,$10,$61,$61,$9B,$5A,$0D,$58,$6F,$72,$5B,$8C,$67,$7B,$9F,$0D,$00
  PromptContinue
  SetPortrait $08,$01,$01
  WriteText $6B,$9A,$66,$91,$50,$10,$08,$0D,$8C,$6D,$FF,$FF,$0D,$00
  PromptContinue
  End
  End
CutsceneScript37_0End::


