; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 42 0", ROMX[$6F48], BANK[$4B]
CutsceneScript42_0::
  SetPortrait $03,$00,$00
  Unknown0E $0E
  Unknown12 $04
  Unknown02
  WriteText "ようこそ<br>ていこくかげきだんへ。<br>マリア・タチバナです。<br>",$00
  PromptContinue
  WriteText "わたしのぶきは じゅうです。<br>しゃげきで はなれたてきも<br>こうげきすることができます。<br>",$00
  PromptContinue
  WriteText "せんじょうでは<br>ちいさなゆだんが<br>はいぼくに つながるわ。<br>",$00
  PromptContinue
  WriteText "きをひきしめて<br>しっかりと<br>がんばりなさい。<br>",$00
  PromptContinue
  End
  End
CutsceneScript42_0End::


