; File initially autogenerated by ./scripts/dump_cutscene_scripts.py

INCLUDE "./game/src/cutscene/include/commands.asm"

INCLUDE "./game/src/cutscene/include/charmap.asm"

SECTION "Cutscene Script 44 0", ROMX[$7071], BANK[$4B]
CutsceneScript44_0::
  SetPortrait $05,$00,$00
  Unknown0E $0F
  Unknown12 $04
  Unknown02
  WriteText "ウチは り こうらん。<br>とくぎは きかいいじりと<br>はつめいなんや!<br>",$00
  PromptContinue
  SetPortrait $05,$01,$01
  WriteText "せんとうのときには<br>ウチがつくった じまんの<br>チビロボを みせたるわ!<br>",$00
  PromptContinue
  WriteText "あんさんの こうぶも<br>ウチが かいぞうしたるから<br>いつでも こえかけてな!<br>",$00
  PromptContinue
  WriteText "ほな よろしゅう<br>たのみまっせ。<br>",$00
  PromptContinue
  End
  End
CutsceneScript44_0End::


