; Autogenerated by ./scripts/dump_cutscene_scripts.py

MACRO End
  db $00
ENDM

MACRO WriteText
  db $01, \#
ENDM

MACRO Unknown02
  db $02
ENDM

MACRO Unknown05
  db $05
  db \1
  db \2
  db \3
  db \4
ENDM

MACRO Unknown06
  db $06
  db \1
  db \2
ENDM

MACRO Unknown07
  db $07, \#
ENDM

MACRO Unknown09
  db $09
  db \1
ENDM

MACRO PromptContinue
  db $0A
ENDM

MACRO Unknown0B
  db $0B
  db \1
ENDM

MACRO Unknown0C
  db $0C
  db \1
ENDM

MACRO Unknown0D
  db $0D
  db \1
  db \2
ENDM

MACRO Unknown0E
  db $0E
  db \1
ENDM

MACRO Unknown0F
  db $0F
  db \1
  db \2
ENDM

MACRO Unknown10
  db $10
  db \1
ENDM

MACRO Unknown11
  db $11
  db \1
ENDM

MACRO Unknown12
  db $12
  db \1
ENDM

MACRO Unknown13
  db $13
  db \1
  db \2
ENDM

MACRO OptionSelect
  db $15, \#
ENDM

MACRO OptionSelectTimed
  db $16, \#
ENDM

MACRO SetPortrait
  db $19
  db \1
  db \2
  db \3
ENDM

MACRO Unknown1A
  db $1A, \#
ENDM

MACRO Unknown1D
  db $1D
ENDM

MACRO Unknown1E
  db $1E
  db \1
ENDM

